"use client";
import Link from "next/link";
import { useState } from "react";
import type { AionLeaderboardMetric } from "@/lib/aion/leaderboard";
type Row={id:string;displayName:string;points:number;weeklyTaps:number;level:number;referrals:number;achievements:number;rank:number;stage:string};
type Data={metric:AionLeaderboardMetric;page:number;limit:number;total:number;ownRank:number|null;leaders:Row[]};
const metrics:AionLeaderboardMetric[]=["points","weekly_taps","level","referrals","achievements"];
const value=(row:Row,metric:AionLeaderboardMetric)=>metric==="weekly_taps"?row.weeklyTaps:metric==="points"?row.points:row[metric];
export function LeaderboardPage({initial}:{initial:Data}){const[data,setData]=useState(initial),[loading,setLoading]=useState(false);async function choose(metric:AionLeaderboardMetric,page=1){setLoading(true);const response=await fetch(`/api/aion/leaderboard?metric=${metric}&page=${page}&limit=25`);if(response.ok)setData(await response.json());setLoading(false)}return <main className="min-h-screen bg-[#020711] p-5 text-white"><div className="mx-auto max-w-5xl py-8"><Link href="/rewards" className="text-xs text-cyan-300">← AIONEX</Link><p className="mt-8 text-[10px] uppercase tracking-[.22em] text-cyan-300">PROJECT AION RANKINGS</p><h1 className="mt-2 text-5xl font-semibold">Evolution leaderboard</h1><p className="mt-3 text-slate-500">Privacy-safe rankings from authoritative points, weekly taps, character progression, referrals, and achievements.</p>{data.ownRank&&<p className="mt-4 rounded-xl border border-violet-300/15 bg-violet-400/[.06] p-3 text-sm text-violet-200">Your current position: #{data.ownRank}</p>}<div className="mt-7 flex flex-wrap gap-2">{metrics.map(metric=><button key={metric} onClick={()=>choose(metric)} className={`rounded-xl px-4 py-2 text-sm capitalize ${data.metric===metric?"bg-cyan-300 text-slate-950":"border border-white/10 text-slate-400"}`}>{metric.replaceAll("_"," ")}</button>)}</div><section className={`mt-5 overflow-hidden rounded-2xl border border-white/10 bg-[#081321] transition ${loading?"opacity-50":""}`}><div className="divide-y divide-white/5">{data.leaders.map(row=><div key={row.id} className="grid grid-cols-[4rem_1fr_auto] items-center p-5"><span className="text-xl text-cyan-300">#{row.rank}</span><div><p>{row.displayName}</p><p className="mt-1 text-[9px] uppercase tracking-wider text-violet-300">{row.stage} · LVL {row.level}</p></div><span className="font-mono text-sm text-slate-300">{value(row,data.metric).toLocaleString()} {data.metric.replace("weekly_taps","taps").toUpperCase()}</span></div>)}</div></section><div className="mt-5 flex justify-between"><button disabled={data.page<=1||loading} onClick={()=>choose(data.metric,data.page-1)} className="rounded-xl border border-white/10 px-4 py-2 text-xs disabled:opacity-30">Previous</button><span className="text-xs text-slate-500">{data.total} ranked creators</span><button disabled={data.page*data.limit>=data.total||loading} onClick={()=>choose(data.metric,data.page+1)} className="rounded-xl border border-white/10 px-4 py-2 text-xs disabled:opacity-30">Next</button></div></div></main>}
