import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
import {fallbackVideoContent,videoContentPackageSchema} from "../lib/content/schema.ts";
import {PUBLICATION_PLATFORMS} from "../lib/platforms/config.ts";
import {validateAudibleAudio} from "../lib/video/audio-validation.ts";
import {validateVideoProbe} from "../lib/video/validation.ts";

test("fallback content is a complete five-scene production package",()=>{const content=videoContentPackageSchema.parse(fallbackVideoContent("2026-07-18"));assert.equal(content.durationSeconds,30);assert.equal(content.scenes.length,5);assert.ok(content.scenes.every(scene=>scene.subtitle&&scene.visual));assert.ok(content.telegramCaption);assert.ok(content.youtubeDescription);});
test("future X and TikTok publishing remain disabled",()=>{assert.equal(PUBLICATION_PLATFORMS.x.enabled,false);assert.equal(PUBLICATION_PLATFORMS.tiktok.enabled,false);assert.equal(PUBLICATION_PLATFORMS.telegram.enabled,true);assert.equal(PUBLICATION_PLATFORMS.youtube.enabled,true);});
test("video validation accepts audible production H.264/AAC and rejects draft scale",()=>{const audio=validateAudibleAudio({duration:30,meanVolumeDb:-21,maxVolumeDb:-1.7,silenceDuration:18,audibleDuration:12}),valid=validateVideoProbe({format:{duration:"30",size:"900000"},streams:[{codec_type:"video",codec_name:"h264",width:1080,height:1920},{codec_type:"audio",codec_name:"aac"}]},true,audio);assert.equal(valid.passed,true);const draft=validateVideoProbe({format:{duration:"30",size:"900000"},streams:[{codec_type:"video",codec_name:"h264",width:270,height:480},{codec_type:"audio",codec_name:"aac"}]},true,audio);assert.equal(draft.passed,false);assert.match(draft.errors.join(" "),/270x480/);});
test("audio validation rejects a silent AAC track",()=>{const silent=validateAudibleAudio({duration:30,meanVolumeDb:-91,maxVolumeDb:-90,silenceDuration:30,audibleDuration:0}),video=validateVideoProbe({format:{duration:"30",size:"900000"},streams:[{codec_type:"video",codec_name:"h264",width:1080,height:1920},{codec_type:"audio",codec_name:"aac"}]},true,silent);assert.equal(video.passed,false);assert.match(video.errors.join(" "),/silent|Audible speech/i);});
test("scheduled automation publishes validated Telegram and two public YouTube variants without X or TikTok",async()=>{const runner=await readFile(new URL("../scripts/run-daily-video-automation.mjs",import.meta.url),"utf8"),telegram=await readFile(new URL("../scripts/publish-daily-telegram-video.mjs",import.meta.url),"utf8"),youtube=await readFile(new URL("../scripts/publish-daily-youtube-video.mjs",import.meta.url),"utf8"),installer=await readFile(new URL("../scripts/install-daily-video-task.ps1",import.meta.url),"utf8");assert.match(runner,/run-local-video-dry-run\.ts/);assert.match(runner,/process\.execPath/);assert.match(runner,/telegram_publish/);assert.match(runner,/youtube_publish/);assert.match(telegram,/validation\?\.audio\?\.passed/);assert.match(telegram,/contentHash/);assert.match(telegram,/ON CONFLICT\(content_hash\)/);assert.match(telegram,/aionexweb3/);assert.match(youtube,/privacyStatus:"public"/);assert.match(youtube,/variant:"short"/);assert.match(youtube,/variant:"video"/);assert.match(youtube,/thumbnails\/set/);assert.match(youtube,/existing\[0\]\?\.video_id/);assert.match(youtube,/errors\.push/);assert.match(installer,/10:00/);assert.match(installer,/15:00/);assert.match(installer,/20:00/);for(const blocked of ["publishX","tiktok.com"])assert.doesNotMatch(`${runner}\n${telegram}\n${youtube}`,new RegExp(blocked,"i"));});

test("local rendering is bounded for low-memory hosts and still produces validated 1080x1920 output",async()=>{const pipeline=await readFile(new URL("../scripts/run-local-video-dry-run.ts",import.meta.url),"utf8");assert.match(pipeline,/REMOTION_RENDER_SCALE/);assert.match(pipeline,/concurrency:1/);assert.match(pipeline,/disallowParallelEncoding:true/);assert.match(pipeline,/scale=1080:1920:flags=lanczos/);});
