import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { BACKGROUND_TEMPLATES, STORY_CATEGORIES, templateForCategory } from "../lib/story/catalog.ts";
import { initialStoryPreviews } from "../lib/story/previews.ts";
import { repetitionRisk, scenarioFingerprint, scoreScenario, textSimilarity } from "../lib/story/scoring.ts";
import { selectStoryCategory } from "../lib/story/selector.ts";
const settings={preferredCategories:[],blockedCategories:[],categoryWeights:{}};

test("daily topic selection rotates away from the previous category",()=>{const first=selectStoryCategory([],settings,"2026-07-15"),second=selectStoryCategory([first.key],settings,"2026-07-16");assert.notEqual(first.key,second.key);assert.ok(STORY_CATEGORIES.some(([key])=>key===second.key));});
test("blocked categories and admin weights control selection",()=>{const selected=selectStoryCategory([],{preferredCategories:["energy"],blockedCategories:[],categoryWeights:{energy:1000}},"weighted");assert.equal(selected.key,"energy");assert.throws(()=>selectStoryCategory([],{preferredCategories:[],blockedCategories:STORY_CATEGORIES.map(([key])=>key),categoryWeights:{}},"none"));});
test("seven-day package contains unique, schema-valid AIONEX stories",()=>{const stories=initialStoryPreviews();assert.equal(stories.length,7);assert.equal(new Set(stories.map(story=>story.categoryKey)).size,7);assert.equal(new Set(stories.map(story=>scenarioFingerprint(story))).size,7);for(const story of stories){assert.equal(story.presenter,"animated_core");assert.equal(story.durationSeconds,50);assert.equal(story.scenes.length,5);assert.match(`${story.title} ${story.narration} ${story.callToAction}`,/AION|AIONEX/i);assert.ok(story.telegramCaption.length<=1024);assert.ok(story.xCaption.length<=280);for(const scene of story.scenes){assert.ok(scene.endSeconds>scene.startSeconds);assert.ok(scene.subtitleText);assert.ok(scene.visualInstructions.length);assert.ok(scene.motionInstructions.length);assert.ok(BACKGROUND_TEMPLATES[scene.backgroundTemplateKey as keyof typeof BACKGROUND_TEMPLATES]);}}});
test("similarity and quality gates reject copied scenarios",()=>{const original=initialStoryPreviews()[0],copy={...original,scenarioKey:"copy"};assert.equal(textSimilarity(original.narration,copy.narration),1);assert.ok(repetitionRisk(copy,[original])>42);const result=scoreScenario(copy,[original],78,42);assert.equal(result.approved,false);assert.ok(result.rejectionReasons.some(reason=>reason.includes("Repetition")));});
test("fresh scenarios pass quality and map to purposeful animated templates",()=>{const stories=initialStoryPreviews();for(const story of stories){const result=scoreScenario(story,[],78,42);assert.equal(result.approved,true,result.rejectionReasons.join(" "));assert.equal(templateForCategory(story.categoryKey),story.scenes[0].backgroundTemplateKey);assert.ok(result.totalScore>=78);}});
test("migration and delivery implementation preserve preview safety and destination separation",async()=>{const migration=await readFile(new URL("../db/migrations/014_aion_story_engine.sql",import.meta.url),"utf8"),delivery=await readFile(new URL("../lib/story/delivery.ts",import.meta.url),"utf8"),publish=await readFile(new URL("../lib/automation/publish.ts",import.meta.url),"utf8");for(const table of ["story_content_categories","story_scenarios","story_scenes","story_quality_scores","story_render_jobs","story_deliveries","story_settings"])assert.match(migration,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(migration,/"publishingEnabled":false/);assert.match(migration,/"previewOnly":true/);assert.match(delivery,/publishTelegram/);assert.match(delivery,/uploadYoutube/);assert.match(delivery,/catch\(error\)[\s\S]*X failed/);assert.match(publish,/TELEGRAM_CHANNEL_ID/);assert.match(publish,/TELEGRAM_ADMIN_CHAT_ID/);});
