"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

export default function SignIn(){
 const[mode,setMode]=useState<"login"|"register">("login"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[username,setUsername]=useState(""),[available,setAvailable]=useState<boolean|null>(null);
 useEffect(()=>{if(mode!=="register"||username.length<3){const id=window.setTimeout(()=>setAvailable(null),0);return()=>window.clearTimeout(id)}const controller=new AbortController(),id=window.setTimeout(()=>void fetch(`/api/user-auth/username?username=${encodeURIComponent(username)}`,{signal:controller.signal}).then(r=>r.json()).then(x=>setAvailable(Boolean(x.available))).catch(()=>{}),350);return()=>{controller.abort();window.clearTimeout(id)}},[mode,username]);
 async function submit(form:FormData){setBusy(true);setMessage("");const response=await fetch(`/api/user-auth/${mode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});const data=await response.json() as {error?:string};if(response.ok)window.location.assign("/profile");else{setMessage(data.error||"Authentication failed.");setBusy(false)}}
 return <main className="grid min-h-screen place-items-center bg-[#030812] p-5 text-white"><section className="dashboard-card w-full max-w-md p-8"><Link href="/" className="font-bold">AIONEX <span className="text-cyan-300">AI</span></Link><p className="dashboard-kicker mt-10">SECURE ACCESS</p><h1 className="mt-2 text-3xl font-semibold">{mode==="login"?"Welcome back":"Create your account"}</h1><div className="mt-6 grid grid-cols-2 rounded-xl bg-white/5 p-1"><button onClick={()=>setMode("login")} className={`rounded-lg py-2 text-sm ${mode==="login"?"bg-cyan-300 text-slate-950":"text-slate-400"}`}>Sign in</button><button onClick={()=>setMode("register")} className={`rounded-lg py-2 text-sm ${mode==="register"?"bg-cyan-300 text-slate-950":"text-slate-400"}`}>Register</button></div><a href="/api/user-auth/google" className="mt-5 block rounded-xl border border-white/10 py-3 text-center text-sm transition hover:border-cyan-300/40">Continue with Google</a><div className="my-5 flex items-center gap-3 text-[10px] text-slate-600"><span className="h-px flex-1 bg-white/10"/>OR<span className="h-px flex-1 bg-white/10"/></div><form action={submit} className="space-y-4">{mode==="register"&&<label className="block text-xs text-slate-400">Username<input name="username" value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} minLength={3} maxLength={24} pattern="[a-z0-9_]+" required className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-300/40"/>{available!==null&&<span className={`mt-1 block text-[10px] ${available?"text-emerald-300":"text-rose-300"}`}>{available?"Username is available":"Username is unavailable"}</span>}</label>}<label className="block text-xs text-slate-400">Email<input name="email" type="email" required autoComplete="email" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-300/40"/></label><label className="block text-xs text-slate-400">Password<input name="password" type="password" minLength={12} required autoComplete={mode==="login"?"current-password":"new-password"} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-300/40"/>{mode==="register"&&<span className="mt-1 block text-[10px] text-slate-600">12+ characters with uppercase, lowercase, number, and symbol.</span>}</label>{message&&<p role="alert" className="text-sm text-rose-300">{message}</p>}<button disabled={busy||mode==="register"&&available===false} className="w-full rounded-xl bg-cyan-300 py-3 font-semibold text-slate-950 disabled:opacity-40">{busy?"Please wait…":mode==="login"?"Sign in":"Create account"}</button></form><Link href="/rewards" className="mt-6 block text-center text-xs text-slate-500">Use Telegram or wallet authentication</Link></section></main>;
}
