import "server-only";

import { createHash, randomBytes, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";
import { promisify } from "node:util";
import { cookies } from "next/headers";
import { neon } from "@neondatabase/serverless";

const scrypt = promisify(scryptCallback), COOKIE="aionex_user_session", TTL=60*60*24*30;
const db=()=>{if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is not configured.");return neon(process.env.DATABASE_URL)};
const hashToken=(token:string)=>createHash("sha256").update(token).digest("hex");
export const normalizeEmail=(value:string)=>value.trim().toLowerCase();
export const normalizeUsername=(value:string)=>value.trim().toLowerCase();
export const validUsername=(value:string)=>/^[a-z0-9_]{3,24}$/.test(normalizeUsername(value));
export const validPassword=(value:string)=>value.length>=12&&value.length<=128&&/[a-z]/.test(value)&&/[A-Z]/.test(value)&&/\d/.test(value)&&/[^A-Za-z0-9]/.test(value);

export async function hashPassword(password:string){const salt=randomBytes(16),derived=await scrypt(password,salt,64) as Buffer;return `scrypt:${salt.toString("base64url")}:${derived.toString("base64url")}`}
export async function verifyPassword(password:string,stored:string){const[,saltText,hashText]=stored.split(":");if(!saltText||!hashText)return false;const expected=Buffer.from(hashText,"base64url"),actual=await scrypt(password,Buffer.from(saltText,"base64url"),expected.length) as Buffer;return actual.length===expected.length&&timingSafeEqual(actual,expected)}
export async function createUserSession(userId:string){const token=randomBytes(32).toString("base64url");await db()`INSERT INTO user_auth_sessions(token_hash,user_id,expires_at) VALUES(${hashToken(token)},${userId}::uuid,NOW()+INTERVAL '30 days')`;await db()`UPDATE reward_users SET last_login=NOW(),updated_at=NOW() WHERE id=${userId}::uuid`;await (await cookies()).set(COOKIE,token,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",path:"/",maxAge:TTL,priority:"high"});return token}
export async function getUserSession(){const token=(await cookies()).get(COOKIE)?.value;if(!token)return null;const rows=await db()`SELECT u.id,u.username,u.email,u.avatar_url,u.referral_code,u.created_at,u.last_login FROM user_auth_sessions s JOIN reward_users u ON u.id=s.user_id WHERE s.token_hash=${hashToken(token)} AND s.expires_at>NOW() AND u.status='active' LIMIT 1`;return rows[0]||null}
export async function logoutUser(){const store=await cookies(),token=store.get(COOKIE)?.value;if(token)await db()`DELETE FROM user_auth_sessions WHERE token_hash=${hashToken(token)}`;store.delete(COOKIE)}
export async function usernameAvailable(username:string,currentUserId?:string){if(!validUsername(username))return false;const rows=await db()`SELECT 1 FROM reward_users WHERE LOWER(username)=${normalizeUsername(username)} AND (${currentUserId||null}::uuid IS NULL OR id<>${currentUserId||null}::uuid) LIMIT 1`;return !rows[0]}
export async function registerUser(username:string,email:string,password:string){username=normalizeUsername(username);email=normalizeEmail(email);if(!validUsername(username)||!/^\S+@\S+\.\S+$/.test(email)||!validPassword(password))throw new Error("Invalid registration details.");const rows=await db()`INSERT INTO reward_users(display_name,username,email,password_hash,referral_code,last_login) VALUES(${username},${username},${email},${await hashPassword(password)},${randomBytes(6).toString("base64url").toUpperCase()},NOW()) RETURNING id`;return String(rows[0].id)}
export async function loginUser(email:string,password:string){const rows=await db()`SELECT id,password_hash FROM reward_users WHERE LOWER(email)=${normalizeEmail(email)} AND status='active' LIMIT 1`;if(!rows[0]?.password_hash||!await verifyPassword(password,String(rows[0].password_hash)))return null;return String(rows[0].id)}
export async function googleUser(profile:{sub:string;email:string;name?:string;picture?:string}){const email=normalizeEmail(profile.email);const existing=await db()`SELECT u.id FROM user_auth_accounts a JOIN reward_users u ON u.id=a.user_id WHERE a.provider='google' AND a.provider_user_id=${profile.sub} LIMIT 1`;if(existing[0]){await db()`UPDATE reward_users SET email=COALESCE(email,${email}),avatar_url=COALESCE(${profile.picture||null},avatar_url),updated_at=NOW() WHERE id=${existing[0].id}`;return String(existing[0].id)}const byEmail=await db()`SELECT id FROM reward_users WHERE LOWER(email)=${email} LIMIT 1`;let userId=byEmail[0]?String(byEmail[0].id):null;if(!userId){const base=normalizeUsername(email.split("@")[0].replace(/[^a-z0-9_]/g,"_")).slice(0,18)||"explorer";let username=base;for(let i=0;!await usernameAvailable(username);i++)username=`${base.slice(0,18)}_${i+1}`;const rows=await db()`INSERT INTO reward_users(display_name,username,email,avatar_url,referral_code,last_login) VALUES(${profile.name||username},${username},${email},${profile.picture||null},${randomBytes(6).toString("base64url").toUpperCase()},NOW()) RETURNING id`;userId=String(rows[0].id)}await db()`INSERT INTO user_auth_accounts(user_id,provider,provider_user_id) VALUES(${userId}::uuid,'google',${profile.sub}) ON CONFLICT(provider,provider_user_id) DO NOTHING`;return userId}
