export const AIONEX_SYSTEM_PROMPT = `You are AIONEX Copilot, the official AI guide for the AIONEX ecosystem.
Be accurate, concise, practical, and transparent. Explain that figures and roadmap dates are project plans, not financial guarantees. Never provide personalized financial advice. Use Markdown when it improves readability.

Ecosystem context:
- AIONEX AI is an on-chain intelligence layer combining AI market tools, community ownership, and transparent blockchain infrastructure.
- The AIONEX token provides ecosystem access, governance participation, and network incentives.
- Token allocation: Community & ecosystem 40%, Liquidity 25%, Development 20%, Team & advisors 10%, Reserve 5%. Total supply: 1 billion AIONEX.
- Roadmap: Foundation in Q3 2026 (token launch, community activation, core platform); Expansion in Q4 2026 (AI tools, integrations, governance); Scale in 2027 (global ecosystem, protocol intelligence, developer grants).
- Staking includes illustrative Flexible, Growth, and Conviction vaults with progressively longer lock periods. Rates shown in the product are estimates, not guarantees.
- Governance uses AIONEX Improvement Proposals and token-based community participation.
- Marketplace is designed for ecosystem collectibles and access assets such as Genesis Nodes, Signal Fragments, Neural Archives, and Founders Passes.
- Dashboard includes market overviews, charts, AI signals, portfolio intelligence, and a news feed.`;

const answers: Array<[RegExp, string]> = [
  [/what is|about aionex|aionex ai/i, `## AIONEX AI\n\nAIONEX AI is an **on-chain intelligence layer** that brings three systems together:\n\n- **AI market intelligence** for clearer signals and analysis\n- **Community ownership** through the AIONEX token and governance\n- **Transparent infrastructure** for open, interoperable Web3 products\n\nThe platform connects a live dashboard, portfolio intelligence, staking, governance, a launchpad, and a digital-asset marketplace in one ecosystem.`],
  [/token|tokenomics|allocation|supply/i, `## AIONEX tokenomics\n\nThe fixed planned supply is **1,000,000,000 AIONEX**.\n\n| Allocation | Share |\n| --- | ---: |\n| Community & ecosystem | 40% |\n| Liquidity | 25% |\n| Development | 20% |\n| Team & advisors | 10% |\n| Reserve | 5% |\n\nThe token is designed for **ecosystem access, governance participation, and network incentives**. Allocation details should be read as project design—not a promise of price or return.`],
  [/roadmap|timeline|when/i, `## AIONEX roadmap\n\n### 01 · Foundation — Q3 2026\n- Token launch\n- Community activation\n- Core platform release\n\n### 02 · Expansion — Q4 2026\n- AI tools suite\n- Strategic integrations\n- Governance launch\n\n### 03 · Scale — 2027\n- Global ecosystem\n- Protocol intelligence\n- Developer grants\n\nRoadmap dates are targets and may evolve as the ecosystem develops.`],
  [/stak|vault|apr|apy/i, `## How staking works\n\nAIONEX staking is designed around three vault profiles:\n\n1. **Flexible** — no lock-up, maximum access to funds\n2. **Growth** — a 90-day commitment for users with a longer horizon\n3. **Conviction** — a 365-day commitment aligned with long-term participation\n\nThe interface may show estimated rates, but these are **not guaranteed returns**. Before depositing, users should review lock terms, smart-contract risk, reward mechanics, and withdrawal conditions.`],
  [/govern|dao|proposal|vote/i, `## AIONEX governance\n\nGovernance lets the community participate in protocol direction through **AIONEX Improvement Proposals (AIPs)**. Proposals can cover areas such as treasury allocation, ecosystem incentives, integrations, and protocol economics.\n\nA typical flow is:\n\n\`Draft → Community discussion → On-chain vote → Execution\`\n\nVoting rules, quorum, delegation, and execution safeguards should be finalized in the governance specification before activation.`],
  [/marketplace|collectible|nft/i, `## AIONEX Marketplace\n\nThe marketplace is the ecosystem hub for intelligent digital assets and access collectibles. Current concepts include **Genesis Nodes, Signal Fragments, Neural Archives, and Founders Passes**.\n\nIt is designed to support discovery, ownership verification, and utility across AIONEX products. Exact rights and benefits should always be verified in an asset's official metadata before purchase.`],
  [/news|latest crypto|market news/i, `## Crypto market news\n\nThe **Dashboard intelligence feed** is the source for live ecosystem news and refreshes regularly through the AIONEX market-news service. Open **Dashboard → AI Market Analysis** for the newest headlines.\n\nI can summarize live stories once a web-search or market-data tool is connected to the production AI provider. Until then, I won't invent current headlines.`],
  [/blockchain trend|ai trend|trends/i, `## AI × blockchain trends\n\nSeveral themes are shaping the space:\n\n- **Verifiable AI:** proving model inputs, outputs, or execution\n- **Agent economies:** autonomous software coordinating payments and services\n- **Decentralized compute:** open markets for training and inference capacity\n- **On-chain intelligence:** translating fragmented blockchain data into useful decisions\n- **Data provenance:** tracking ownership, consent, and lineage for AI datasets\n\nAIONEX is positioned primarily around the on-chain intelligence and community-coordination layers.`],
];

export function answerFromKnowledge(question: string) {
  const answer = answers.find(([pattern]) => pattern.test(question))?.[1];
  return answer ?? `I can help you navigate the complete **AIONEX ecosystem**—including tokenomics, the roadmap, staking, governance, marketplace assets, portfolio intelligence, market signals, and platform architecture.\n\nTry asking a focused question such as **“How does the AIONEX token connect governance and staking?”** and I’ll break it down step by step.`;
}
