"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { AdminSection, AdminUser, ManagedContent } from "@/types/admin";

const navigation: Array<[AdminSection, string, string]> = [["overview", "Overview", "◫"], ["users", "Users", "◎"], ["ai", "AI Content", "✦"], ["news", "News", "⌁"], ["market", "Markets", "↗"], ["token", "Token", "◇"], ["analytics", "Analytics", "∆"]];
const initialUsers: AdminUser[] = [{ id: "USR-1048", address: "0x71C4…91e2", status: "Active", joined: "Jul 12, 2026", activity: "2m ago" }, { id: "USR-1047", address: "0x39A8…4Fb1", status: "Active", joined: "Jul 12, 2026", activity: "18m ago" }, { id: "USR-1046", address: "0xB211…81C0", status: "Suspended", joined: "Jul 11, 2026", activity: "1d ago" }, { id: "USR-1045", address: "0x0D74…A992", status: "Active", joined: "Jul 10, 2026", activity: "3h ago" }];
const initialContent: ManagedContent[] = [{ id: "AI-026", title: "Understanding the AIONEX intelligence layer", category: "Education", status: "Published", updated: "12 min ago" }, { id: "AI-025", title: "Weekly on-chain market brief", category: "Analysis", status: "Draft", updated: "1h ago" }, { id: "AI-024", title: "Governance participation guide", category: "Governance", status: "Published", updated: "Yesterday" }];

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-white/[.08] bg-[#081321]/75 shadow-[inset_0_1px_rgba(255,255,255,.03)] ${className}`}>{children}</section>; }
function Status({ children, tone = "cyan" }: { children: React.ReactNode; tone?: "cyan" | "amber" | "green" }) { const styles = tone === "green" ? "bg-emerald-300/10 text-emerald-300" : tone === "amber" ? "bg-amber-300/10 text-amber-200" : "bg-cyan-300/10 text-cyan-200"; return <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${styles}`}>{children}</span>; }

export function AdminDashboard({ adminEmail }: { adminEmail: string }) {
  const router = useRouter();
  const [section, setSection] = useState<AdminSection>("overview");
  const [mobileNav, setMobileNav] = useState(false);
  const [users, setUsers] = useState(initialUsers);
  const [content, setContent] = useState(initialContent);
  const [saved, setSaved] = useState(false);

  async function logout() { await fetch("/api/admin/logout", { method: "POST" }); router.replace("/admin/login"); router.refresh(); }
  function select(next: AdminSection) { setSection(next); setMobileNav(false); }
  function save() { setSaved(true); window.setTimeout(() => setSaved(false), 1800); }

  return <main className="min-h-screen bg-[#020711] text-white"><header className="fixed inset-x-0 top-0 z-50 flex h-16 items-center justify-between border-b border-white/[.07] bg-[#030914]/90 px-4 backdrop-blur-xl sm:px-6"><div className="flex items-center gap-3"><button onClick={() => setMobileNav(true)} className="grid h-9 w-9 place-items-center rounded-lg border border-white/10 text-cyan-200 lg:hidden">☰</button><Link href="/" className="font-bold tracking-tight">AIONEX <span className="text-cyan-300">AI</span></Link><span className="hidden rounded-md border border-cyan-300/15 bg-cyan-300/[.06] px-2 py-1 text-[9px] font-semibold tracking-widest text-cyan-200 sm:inline">ADMIN</span></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><p className="text-xs text-slate-300">{adminEmail}</p><p className="text-[10px] text-emerald-300">● Authenticated</p></div><button onClick={logout} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-400 transition hover:border-rose-300/20 hover:text-rose-300">Sign out</button></div></header>

    {mobileNav && <button aria-label="Close navigation" onClick={() => setMobileNav(false)} className="fixed inset-0 z-50 bg-black/60 lg:hidden" />}
    <aside className={`fixed bottom-0 left-0 top-16 z-[60] w-64 border-r border-white/[.07] bg-[#050c17]/95 p-4 backdrop-blur-xl transition-transform lg:z-40 lg:translate-x-0 ${mobileNav ? "translate-x-0" : "-translate-x-full"}`}><p className="mb-3 px-3 text-[9px] font-semibold uppercase tracking-[.2em] text-slate-600">Control plane</p><nav className="space-y-1">{navigation.map(([key, label, icon]) => <button key={key} onClick={() => select(key)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition ${section === key ? "bg-cyan-300/10 text-cyan-100" : "text-slate-500 hover:bg-white/[.035] hover:text-slate-200"}`}><span className={`grid h-7 w-7 place-items-center rounded-lg text-xs ${section === key ? "bg-cyan-300/10 text-cyan-300" : "bg-white/[.03]"}`}>{icon}</span>{label}</button>)}</nav><div className="absolute inset-x-4 bottom-4 rounded-xl border border-cyan-300/10 bg-cyan-300/[.035] p-3"><p className="text-[10px] font-semibold text-cyan-200">System healthy</p><p className="mt-1 text-[10px] text-slate-600">All services operational</p></div></aside>

    <div className="min-h-screen pt-16 lg:pl-64"><div className="mx-auto max-w-[1500px] p-4 sm:p-7 lg:p-9"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="dashboard-kicker">AIONEX OPERATIONS</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{navigation.find(([key]) => key === section)?.[1]}</h1><p className="mt-2 text-sm text-slate-500">Manage and monitor the intelligence ecosystem.</p></div><div className="flex gap-2"><button className="rounded-xl border border-white/10 px-4 py-2.5 text-xs text-slate-300 transition hover:bg-white/5">Export data</button><button onClick={save} className="rounded-xl bg-cyan-300 px-4 py-2.5 text-xs font-semibold text-slate-950 transition hover:bg-cyan-200">{saved ? "Saved ✓" : "Save changes"}</button></div></div>
      {section === "overview" && <Overview />}
      {section === "users" && <Users users={users} setUsers={setUsers} />}
      {section === "ai" && <ContentManager title="AI content library" items={content} setItems={setContent} />}
      {section === "news" && <ContentManager title="Newsroom" items={[{ id: "NEWS-91", title: "Institutional flows return to digital assets", category: "Market", status: "Published", updated: "8 min ago" }, { id: "NEWS-90", title: "Protocol intelligence weekly", category: "Research", status: "Draft", updated: "42 min ago" }]} />}
      {section === "market" && <MarketManager />}
      {section === "token" && <TokenSettings />}
      {section === "analytics" && <Analytics />}
    </div></div>
  </main>;
}

function Overview() { const stats = [["Total users", "24,891", "+12.4%"], ["Active wallets", "8,429", "+8.1%"], ["AI requests", "1.28M", "+24.7%"], ["Protocol TVL", "$18.4M", "+5.3%"]]; return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value, change]) => <Card key={label} className="p-5"><div className="flex justify-between"><p className="text-xs text-slate-500">{label}</p><span className="text-[10px] text-emerald-300">{change}</span></div><p className="mt-4 text-3xl font-semibold tracking-tight">{value}</p><div className="mt-5 h-1 overflow-hidden rounded-full bg-white/5"><div className="h-full w-2/3 rounded-full bg-gradient-to-r from-cyan-400 to-blue-500" /></div></Card>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><Card className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Platform activity</p><p className="mt-1 text-xs text-slate-500">30-day ecosystem usage</p></div><Status>LIVE</Status></div><div className="mt-8 flex h-56 items-end gap-2">{[32,45,38,61,54,72,66,84,69,78,88,92,76,95].map((height, index) => <div key={index} className="group flex-1 rounded-t bg-gradient-to-t from-blue-600/30 to-cyan-300/60 transition hover:to-cyan-200" style={{ height: `${height}%` }} />)}</div></Card><Card className="p-5 sm:p-6"><p className="text-sm font-semibold">System status</p><div className="mt-6 space-y-4">{[["AI Assistant", "Operational"], ["Market data", "Operational"], ["Wallet RPC", "Operational"], ["News service", "Operational"]].map(([service, status]) => <div key={service} className="flex items-center justify-between"><span className="text-xs text-slate-400">{service}</span><span className="flex items-center gap-2 text-[10px] text-emerald-300"><i className="h-1.5 w-1.5 rounded-full bg-emerald-300" />{status}</span></div>)}</div></Card></div></>; }

function Users({ users, setUsers }: { users: AdminUser[]; setUsers: React.Dispatch<React.SetStateAction<AdminUser[]>> }) { return <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-white/[.07] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">User directory</p><p className="mt-1 text-xs text-slate-500">Wallet identities and access state</p></div><input placeholder="Search address or ID…" className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-xs outline-none focus:border-cyan-300/30" /></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead className="text-[10px] uppercase tracking-wider text-slate-600"><tr>{["User", "Wallet", "Joined", "Last active", "Status", "Action"].map((head) => <th key={head} className="px-5 py-3 font-semibold">{head}</th>)}</tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-t border-white/[.055] text-xs text-slate-400"><td className="px-5 py-4 font-medium text-slate-200">{user.id}</td><td className="px-5 py-4 font-mono">{user.address}</td><td className="px-5 py-4">{user.joined}</td><td className="px-5 py-4">{user.activity}</td><td className="px-5 py-4"><Status tone={user.status === "Active" ? "green" : "amber"}>{user.status}</Status></td><td className="px-5 py-4"><button onClick={() => setUsers((current) => current.map((item) => item.id === user.id ? { ...item, status: item.status === "Active" ? "Suspended" : "Active" } : item))} className="text-cyan-300 hover:underline">{user.status === "Active" ? "Suspend" : "Restore"}</button></td></tr>)}</tbody></table></div></Card>; }

function ContentManager({ title, items, setItems }: { title: string; items: ManagedContent[]; setItems?: React.Dispatch<React.SetStateAction<ManagedContent[]>> }) { return <div className="grid gap-5 xl:grid-cols-[1fr_20rem]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-white/[.07] p-5"><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-slate-500">Review publishing workflow</p></div><button className="rounded-lg bg-cyan-300/10 px-3 py-2 text-xs text-cyan-200">+ New item</button></div><div className="divide-y divide-white/[.055]">{items.map((item) => <article key={item.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><span className="text-[10px] text-slate-600">{item.id}</span><Status tone={item.status === "Published" ? "green" : "amber"}>{item.status}</Status></div><h3 className="mt-2 text-sm font-medium text-slate-200">{item.title}</h3><p className="mt-1 text-xs text-slate-600">{item.category} · Updated {item.updated}</p></div><button onClick={() => setItems?.((current) => current.map((entry) => entry.id === item.id ? { ...entry, status: entry.status === "Published" ? "Draft" : "Published" } : entry))} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-400 hover:text-cyan-200">{item.status === "Published" ? "Unpublish" : "Publish"}</button></article>)}</div></Card><Card className="p-5"><p className="text-sm font-semibold">Content health</p><div className="mt-6 grid place-items-center"><div className="grid h-32 w-32 place-items-center rounded-full border-[10px] border-cyan-300/15 border-t-cyan-300"><div className="text-center"><p className="text-2xl font-semibold">94%</p><p className="text-[9px] text-slate-500">QUALITY</p></div></div></div><p className="mt-6 text-xs leading-6 text-slate-500">AI-generated content should pass human review before publication.</p></Card></div>; }

function MarketManager() { return <div className="grid gap-5 lg:grid-cols-3">{[["Price feeds", "CoinGecko Pro", "Connected"], ["News feeds", "Cointelegraph RSS", "Connected"], ["Chart data", "TradingView", "Connected"]].map(([name, source, state]) => <Card key={name} className="p-5"><div className="flex justify-between"><span className="text-sm font-semibold">{name}</span><Status tone="green">{state}</Status></div><p className="mt-2 text-xs text-slate-500">Provider: {source}</p><div className="mt-7 flex gap-2"><button className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-400">Configure</button><button className="rounded-lg bg-cyan-300/10 px-3 py-2 text-xs text-cyan-200">Test feed</button></div></Card>)}</div>; }

function TokenSettings() { return <div className="grid gap-5 xl:grid-cols-[1fr_.65fr]"><Card className="p-5 sm:p-6"><p className="text-sm font-semibold">AIONEX token configuration</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{[["Token name", "AIONEX"], ["Symbol", "AIONEX"], ["Total supply", "1,000,000,000"], ["Decimals", "18"], ["Network", "Ethereum"], ["Contract", "Not deployed"]].map(([label, value]) => <label key={label}><span className="mb-2 block text-[10px] uppercase tracking-wider text-slate-600">{label}</span><input defaultValue={value} className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-slate-300 outline-none focus:border-cyan-300/30" /></label>)}</div></Card><Card className="p-5 sm:p-6"><div className="flex justify-between"><p className="text-sm font-semibold">Safety controls</p><Status tone="amber">PRE-LAUNCH</Status></div><div className="mt-6 space-y-3">{["Require multisig approval", "Pause transfers", "Governance timelock", "Contract verification"].map((item, index) => <label key={item} className="flex items-center justify-between rounded-xl border border-white/[.06] p-3 text-xs text-slate-400"><span>{item}</span><input type="checkbox" defaultChecked={index !== 1} className="accent-cyan-300" /></label>)}</div></Card></div>; }

function Analytics() { return <div className="grid gap-5 lg:grid-cols-2"><Card className="p-6"><p className="text-sm font-semibold">Acquisition channels</p><div className="mt-7 space-y-5">{[["Organic", 72], ["Community", 58], ["Partners", 41], ["Direct", 34]].map(([label, value]) => <div key={label as string}><div className="mb-2 flex justify-between text-xs"><span className="text-slate-400">{label}</span><span className="text-slate-600">{value}%</span></div><div className="h-2 rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-blue-500" style={{ width: `${value}%` }} /></div></div>)}</div></Card><Card className="p-6"><p className="text-sm font-semibold">Feature adoption</p><div className="mt-6 grid grid-cols-2 gap-3">{[["Dashboard", "82%"], ["AI Copilot", "68%"], ["Portfolio", "51%"], ["Governance", "27%"]].map(([label, value]) => <div key={label} className="rounded-xl border border-white/[.06] bg-black/10 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-cyan-100">{value}</p></div>)}</div></Card></div>; }
