"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
const modules=[
 {href:"/admin/posts",title:"Publishing",description:"Review, approve, publish, and retry website, Telegram, and X posts."},
 {href:"/admin/rewards",title:"Rewards & tasks",description:"Manage tasks, AXP, XP, mining configuration, users, and risk state."},
 {href:"/admin/social",title:"Social verification",description:"Manage official links, verification statistics, completed users, and resets."},
 {href:"/admin/claims",title:"Claim moderation",description:"Review pending X, YouTube, Telegram, and manual task claims."},
];
export function AdminDashboard({adminUsername,adminEmail,role}:{adminUsername:string;adminEmail:string;role:"admin"}){const router=useRouter();async function logout(){await fetch("/api/admin/logout",{method:"POST"});router.replace("/admin/login");router.refresh();}return <main className="min-h-screen bg-[#020711] p-5 text-white sm:p-8"><div className="mx-auto max-w-6xl"><header className="flex flex-col justify-between gap-4 border-b border-white/10 pb-6 sm:flex-row sm:items-center"><div><Link href="/" className="font-bold">AIONEX <span className="text-cyan-300">ADMIN</span></Link><p className="mt-2 text-xs text-slate-500">Signed in as {adminUsername} · {adminEmail} · {role}</p></div><button onClick={logout} className="rounded-xl border border-white/10 px-4 py-2 text-xs text-slate-300 hover:border-rose-300/30 hover:text-rose-200">Sign out</button></header><section className="py-10"><p className="text-xs tracking-[.22em] text-cyan-300">PRODUCTION CONTROL PLANE</p><h1 className="mt-3 text-4xl font-semibold sm:text-6xl">Operate AIONEX safely.</h1><p className="mt-4 max-w-2xl text-slate-400">Every module below is backed by authenticated APIs and PostgreSQL. No simulated statistics or local-only editors are shown.</p><div className="mt-8 grid gap-4 md:grid-cols-2">{modules.map(module=><Link key={module.href} href={module.href} className="group rounded-2xl border border-white/10 bg-[#081321] p-6 transition hover:-translate-y-0.5 hover:border-cyan-300/30"><h2 className="text-xl font-semibold group-hover:text-cyan-200">{module.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{module.description}</p><span className="mt-5 block text-xs text-cyan-300">Open module →</span></Link>)}</div></section></div></main>}
