"use client";

import { useEffect, useState } from "react";

type Template = { id: string; title: string; key: string; enabled: boolean; reward_axp: number; reward_xp: number; reward_energy: number; reward_chest_progress: number; reward_streak_progress: number };
type State = { period: null | { period_date: string; status: string; task_count: number; assignment_count: number; notification_status: string; last_error?: string }; runs: Array<{ id: string; status: string; trigger_source: string; started_at: string; error_message?: string }>; templates: Template[]; nextPreview: Array<{ externalKey: string; title: string }> };

export function DailyTaskManager() {
  const [state, setState] = useState<State | null>(null);
  const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/admin/rewards/daily-tasks", { cache: "no-store" }); if (response.ok) setState(await response.json()); }
  useEffect(() => { let active = true; fetch("/api/admin/rewards/daily-tasks", { cache: "no-store" }).then(response => response.ok ? response.json() : null).then(data => { if (active && data) setState(data); }); return () => { active = false; }; }, []);
  async function refresh(notify: boolean) { setMessage("Refreshing..."); const response = await fetch("/api/admin/rewards/daily-tasks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "refresh", notify }) }); setMessage(response.ok ? "Daily tasks refreshed idempotently." : "Refresh failed."); await load(); }
  async function save(template: Template) { const response = await fetch("/api/admin/rewards/daily-tasks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "update-template", id: template.id, template: { enabled: template.enabled, rewardAxp: Number(template.reward_axp), rewardXp: Number(template.reward_xp), rewardEnergy: Number(template.reward_energy), rewardChestProgress: Number(template.reward_chest_progress), rewardStreakProgress: Number(template.reward_streak_progress) } }) }); setMessage(response.ok ? `${template.title} template saved for the next generated period.` : "Template update failed."); await load(); }
  const update = (id: string, change: Partial<Template>) => setState(current => current ? { ...current, templates: current.templates.map(item => item.id === id ? { ...item, ...change } : item) } : current);
  return <section className="mt-8 rounded-2xl border border-white/10 bg-[#081321] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.2em] text-cyan-300">UTC DAILY REFRESH</p><h2 className="mt-1">Daily task scheduler</h2></div><div className="flex gap-2"><button onClick={() => refresh(false)} className="border border-cyan-300/30 px-3 py-2 text-xs">Recover / refresh</button><button onClick={() => refresh(true)} className="bg-cyan-300 px-3 py-2 text-xs text-slate-950">Refresh + notify</button></div></div>{message && <p className="mt-3 text-xs text-cyan-200">{message}</p>}<p className="mt-3 text-xs text-slate-400">{state?.period ? `${String(state.period.period_date).slice(0,10)} · ${state.period.status} · ${state.period.task_count} tasks · ${state.period.assignment_count} assignments · notification ${state.period.notification_status}` : "No generated period found."}</p>{state?.period?.last_error && <p className="mt-2 text-xs text-rose-300">{state.period.last_error}</p>}<details className="mt-3 text-xs text-slate-400"><summary>Preview next task set ({state?.nextPreview.length || 0})</summary><ul className="mt-2 list-disc pl-5">{state?.nextPreview.map(item => <li key={item.externalKey}>{item.title}</li>)}</ul></details><div className="mt-4 grid gap-3 lg:grid-cols-2">{state?.templates.map(template => <article key={template.id} className="rounded-xl border border-white/10 p-3"><div className="flex justify-between"><strong className="text-sm">{template.title}</strong><label className="text-xs"><input type="checkbox" checked={template.enabled} onChange={event => update(template.id, { enabled: event.target.checked })}/> enabled</label></div><div className="mt-3 grid grid-cols-5 gap-2">{([['reward_axp','AXP'],['reward_xp','XP'],['reward_energy','Energy'],['reward_chest_progress','Chest'],['reward_streak_progress','Streak']] as const).map(([key,label]) => <label key={key} className="text-[10px] text-slate-500">{label}<input aria-label={`${template.title} ${label}`} type="number" min="0" value={template[key]} onChange={event => update(template.id, { [key]: Number(event.target.value) })} className="mt-1 w-full bg-black/20 p-2 text-white"/></label>)}</div><button onClick={() => save(template)} className="mt-3 text-xs text-cyan-300">Save template</button></article>)}</div><div className="mt-4 text-[10px] text-slate-500">Last runs: {state?.runs.slice(0,3).map(run => `${run.status} (${run.trigger_source})`).join(" · ") || "none"}</div></section>;
}
