"use client";

import Link from "next/link";
import { useState } from "react";
import type { AutomationPost } from "@/lib/automation/types";

export function PostManager({ initialPosts, initialError = "" }: { initialPosts: AutomationPost[]; initialError?: string }) {
  const [posts, setPosts] = useState<AutomationPost[]>(initialPosts), [selected, setSelected] = useState<AutomationPost | null>(initialPosts[0] || null), [message, setMessage] = useState(initialError || (initialPosts.length ? "" : "No posts yet.")), [busy, setBusy] = useState(false);
  async function load() { const response = await fetch("/api/admin/posts", { cache: "no-store" }); const data = await response.json(); if (!response.ok) return setMessage(data.error); setPosts(data.posts); setSelected((current) => data.posts.find((post: AutomationPost) => post.id === current?.id) || data.posts[0] || null); setMessage(data.posts.length ? "" : "No posts yet."); }
  async function generate() { setBusy(true); setMessage("Generating today’s draft…"); const response = await fetch("/api/admin/posts", { method: "POST" }); const data = await response.json(); setMessage(response.ok ? "Draft ready." : data.error); await load(); setBusy(false); }
  async function save(status = selected?.status) { if (!selected || !status) return; setBusy(true); const response = await fetch(`/api/admin/posts/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...selected, status }) }); const data = await response.json(); setMessage(response.ok ? "Post saved." : data.error); if (response.ok) setSelected(data.post); await load(); setBusy(false); }
  async function publish() { if (!selected) return; setBusy(true); setMessage("Publishing to Telegram and X…"); const response = await fetch(`/api/admin/posts/${selected.id}/publish`, { method: "POST" }); const data = await response.json(); setMessage(response.ok ? (data.post.status === "published" ? "Published everywhere." : data.post.lastError) : data.error); await load(); setBusy(false); }
  const field = (key: "title" | "excerpt" | "body" | "socialText", rows = 1) => rows > 1 ? <textarea value={selected?.[key] || ""} rows={rows} onChange={(e) => selected && setSelected({ ...selected, [key]: e.target.value })} className="w-full rounded-xl border border-white/10 bg-black/30 p-3 text-sm text-slate-200 outline-none focus:border-cyan-300/40" /> : <input value={selected?.[key] || ""} onChange={(e) => selected && setSelected({ ...selected, [key]: e.target.value })} className="w-full rounded-xl border border-white/10 bg-black/30 p-3 text-sm text-slate-200 outline-none focus:border-cyan-300/40" />;
  return <main className="min-h-screen bg-[#020711] p-5 text-white sm:p-8"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/admin" className="text-xs text-cyan-300">← Admin dashboard</Link><h1 className="mt-3 text-3xl font-semibold">Daily publishing</h1><p className="mt-2 text-sm text-slate-500">Review, edit, approve, and retry cross-channel posts.</p></div><button disabled={busy} onClick={generate} className="rounded-xl bg-cyan-300 px-4 py-3 text-sm font-semibold text-slate-950 disabled:opacity-50">Generate today’s draft</button></header>{message && <p className="mt-5 rounded-xl border border-cyan-300/15 bg-cyan-300/5 p-3 text-sm text-cyan-100">{message}</p>}<div className="mt-6 grid gap-5 lg:grid-cols-[20rem_1fr]"><aside className="space-y-2">{posts.map((post) => <button key={post.id} onClick={() => setSelected(post)} className={`w-full rounded-xl border p-4 text-left ${selected?.id === post.id ? "border-cyan-300/30 bg-cyan-300/5" : "border-white/10 bg-white/[.02]"}`}><span className="text-[10px] uppercase text-cyan-300">{post.scheduledFor} · {post.status}</span><p className="mt-2 text-sm text-slate-200">{post.title}</p><p className="mt-2 text-[10px] text-slate-500">Telegram: {post.telegramStatus} · X: {post.xStatus}</p></button>)}</aside>{selected && <section className="space-y-4 rounded-2xl border border-white/10 bg-[#081321]/75 p-5"><label className="block text-xs text-slate-500">Title{field("title")}</label><label className="block text-xs text-slate-500">Excerpt{field("excerpt", 3)}</label><label className="block text-xs text-slate-500">Website article (Markdown){field("body", 14)}</label><label className="block text-xs text-slate-500">Telegram/X text ({selected.socialText.length}/280){field("socialText", 4)}</label>{selected.lastError && <p className="rounded-xl bg-rose-400/10 p-3 text-xs text-rose-200">{selected.lastError}</p>}<div className="flex flex-wrap gap-2"><button disabled={busy} onClick={() => save("draft")} className="rounded-lg border border-white/10 px-4 py-2 text-sm">Save draft</button><button disabled={busy} onClick={() => save("approved")} className="rounded-lg bg-amber-300 px-4 py-2 text-sm font-semibold text-slate-950">Approve</button><button disabled={busy || selected.status === "draft"} onClick={publish} className="rounded-lg bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-40">Publish / retry</button></div></section>}</div></div></main>;
}
