"use client";
import Link from "next/link";
import { useState } from "react";
import type { StorySettings } from "@/lib/story/types";

type Row=Record<string,unknown>;
type Overview={settings:StorySettings;categories:readonly (readonly [string,string])[];scenarios:Row[];renders:Row[];deliveries:Row[]};
export function StoryManager({initial}:{initial:Overview}){const[data,setData]=useState(initial),[busy,setBusy]=useState(""),[message,setMessage]=useState("");async function action(action:string,extra:Record<string,unknown>={}){setBusy(action);setMessage("");try{const response=await fetch("/api/admin/story",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...extra})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Story Engine action failed.");setData(body.overview);setMessage(`${action.replace("-"," ")} completed safely.`);}catch(error){setMessage(error instanceof Error?error.message:"Story Engine action failed.");}finally{setBusy("");}}const settings=data.settings;const patch=(key:keyof StorySettings,value:unknown)=>action("settings",{settings:{[key]:value}});return <main className="min-h-screen bg-[#020711] p-5 text-white sm:p-8"><div className="mx-auto max-w-7xl"><Link href="/admin" className="text-xs text-cyan-300">← Admin dashboard</Link><p className="mt-8 text-[10px] uppercase tracking-[.24em] text-cyan-300">AIONEX STORY ENGINE</p><h1 className="mt-2 text-4xl font-semibold">Daily media studio</h1><p className="mt-3 max-w-3xl text-sm text-slate-400">AIONEX-first topic rotation, quality gates, anti-repetition, animated vertical rendering, and idempotent delivery. Public publishing remains disabled while preview mode is active.</p>{message&&<p className="mt-5 rounded-xl border border-cyan-300/20 bg-cyan-300/[.05] p-3 text-xs text-cyan-100">{message}</p>}
<section className="mt-8 grid gap-3 md:grid-cols-3">{[["generationEnabled","Automatic generation"],["renderingEnabled","Automatic rendering"],["publishingEnabled","Automatic publishing"],["dryRun","Dry-run mode"],["previewOnly","Preview-only mode"],["emergencyPause","Emergency pause"]].map(([key,label])=><button key={key} onClick={()=>void patch(key as keyof StorySettings,!settings[key as keyof StorySettings])} className={`rounded-2xl border p-4 text-left ${settings[key as keyof StorySettings]?"border-cyan-300/25 bg-cyan-300/[.07]":"border-white/10 bg-[#081321]"}`}><p className="text-xs text-slate-400">{label}</p><p className="mt-2 font-semibold">{settings[key as keyof StorySettings]?"Enabled":"Disabled"}</p></button>)}</section>
<section className="mt-5 grid gap-3 md:grid-cols-4"><Setting label="Daily time" value={settings.dailyTime} onSave={value=>patch("dailyTime",value)}/><Setting label="Timezone" value={settings.timezone} onSave={value=>patch("timezone",value)}/><Setting label="Duration seconds" value={settings.durationSeconds} type="number" onSave={value=>patch("durationSeconds",Number(value))}/><Setting label="Voice" value={settings.voice} onSave={value=>patch("voice",value)}/><Setting label="Repetition limit" value={settings.repetitionThreshold} type="number" onSave={value=>patch("repetitionThreshold",Number(value))}/><Setting label="Minimum quality" value={settings.minimumQualityScore} type="number" onSave={value=>patch("minimumQualityScore",Number(value))}/><Setting label="Daily limit" value={settings.dailyVideoLimit} type="number" onSave={value=>patch("dailyVideoLimit",Number(value))}/><Setting label="Script tone" value={settings.tone} onSave={value=>patch("tone",value)}/><Setting label="Background style" value={settings.backgroundStyle} onSave={value=>patch("backgroundStyle",value)}/><Setting label="Subtitle style" value={settings.subtitleStyle} onSave={value=>patch("subtitleStyle",value)}/><Setting label="Call to action" value={settings.callToAction} onSave={value=>patch("callToAction",value)}/><div className="rounded-2xl border border-white/10 bg-[#081321] p-4"><p className="text-[9px] uppercase tracking-wider text-slate-500">Presenter abstraction</p><p className="mt-2 text-sm">animated_core</p><p className="mt-1 text-[9px] text-slate-600">human_avatar ready</p></div></section>
<section className="mt-6"><h2 className="text-sm font-semibold">Category rotation</h2><p className="mt-1 text-[10px] text-slate-500">Click to cycle normal → preferred → blocked.</p><div className="mt-3 flex flex-wrap gap-2">{data.categories.map(([key,label])=>{const preferred=settings.preferredCategories.includes(key),blocked=settings.blockedCategories.includes(key);return <button key={key} onClick={()=>{const preferredCategories=settings.preferredCategories.filter(item=>item!==key),blockedCategories=settings.blockedCategories.filter(item=>item!==key);if(!preferred&&!blocked)preferredCategories.push(key);else if(preferred)blockedCategories.push(key);void action("settings",{settings:{preferredCategories,blockedCategories}})}} className={`rounded-full border px-3 py-2 text-[9px] ${blocked?"border-rose-300/25 bg-rose-300/[.08] text-rose-200":preferred?"border-cyan-300/25 bg-cyan-300/[.08] text-cyan-200":"border-white/10 text-slate-500"}`}>{label}</button>})}</div></section>
<div className="mt-6 flex flex-wrap gap-3"><button disabled={Boolean(busy)} onClick={()=>void action("seed-week")} className="rounded-xl bg-cyan-300 px-4 py-3 text-xs font-black text-slate-950">Generate seven previews</button><button disabled={Boolean(busy)} onClick={()=>void action("generate")} className="rounded-xl border border-cyan-300/25 px-4 py-3 text-xs text-cyan-200">Generate daily scenario</button></div>
<section className="mt-10"><h2 className="text-xl font-semibold">Scenario history</h2><div className="mt-4 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-white/[.04] text-slate-500"><tr>{["Title","Category","Quality","Repetition","Status","Action"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{data.scenarios.map(row=><tr key={String(row.id)} className="border-t border-white/[.06]"><td className="p-3">{String(row.title)}</td><td className="p-3 text-cyan-300">{String(row.category_key)}</td><td className="p-3">{String(row.quality_score)}</td><td className="p-3">{String(row.repetition_score)}</td><td className="p-3">{String(row.status)}</td><td className="p-3"><button disabled={Boolean(busy)||row.status==="rejected"} onClick={()=>void action("render",{scenarioId:row.id})} className="rounded-lg border border-violet-300/20 px-3 py-2 text-violet-200">Private preview</button></td></tr>)}</tbody></table></div></section>
<div className="mt-10 grid gap-5 lg:grid-cols-2"><History title="Render history" rows={data.renders}/><History title="Platform deliveries" rows={data.deliveries}/></div></div></main>}
function History({title,rows}:{title:string;rows:Row[]}){return <section><h2 className="text-xl font-semibold">{title}</h2><div className="mt-4 space-y-2">{rows.slice(0,15).map((row,index)=><div key={String(row.id||index)} className="rounded-xl border border-white/10 bg-[#081321] p-3 text-xs"><p>{String(row.title||row.platform||"Story job")}</p><p className="mt-1 text-slate-500">{String(row.status)}{row.last_error?` · ${String(row.last_error).slice(0,120)}`:""}</p></div>)}{!rows.length&&<p className="text-xs text-slate-500">No records yet.</p>}</div></section>}
function Setting({label,value,type="text",onSave}:{label:string;value:string|number;type?:string;onSave:(value:string)=>void|Promise<void>}){return <label className="rounded-2xl border border-white/10 bg-[#081321] p-4"><span className="text-[9px] uppercase tracking-wider text-slate-500">{label}</span><input type={type} defaultValue={value} onBlur={event=>{if(event.target.value!==String(value))void onSave(event.target.value)}} className="mt-2 w-full bg-transparent text-sm outline-none focus:text-cyan-200"/></label>}
