import "server-only";
import { createCipheriv, createDecipheriv, createHash, randomBytes } from "node:crypto";
import { neon } from "@neondatabase/serverless";
const sql=()=>{if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is not configured.");return neon(process.env.DATABASE_URL)};
const clientId=()=>process.env.GOOGLE_CLIENT_ID||process.env.YOUTUBE_CLIENT_ID||"";
const clientSecret=()=>process.env.GOOGLE_CLIENT_SECRET||process.env.YOUTUBE_CLIENT_SECRET||"";
const key=()=>createHash("sha256").update(process.env.AUTH_SECRET||"").digest();
function encrypt(value:string){const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key(),iv),body=Buffer.concat([cipher.update(value),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString("base64url")}
function decrypt(value:string){const raw=Buffer.from(value,"base64url"),decipher=createDecipheriv("aes-256-gcm",key(),raw.subarray(0,12));decipher.setAuthTag(raw.subarray(12,28));return Buffer.concat([decipher.update(raw.subarray(28)),decipher.final()]).toString()}
export function youtubeRedirectUri(){return process.env.GOOGLE_REDIRECT_URI||`${process.env.NEXT_PUBLIC_SITE_URL}/api/admin/youtube/oauth/callback`}
export function youtubeAuthorizationUrl(state:string){const id=clientId();if(!id)throw new Error("GOOGLE_CLIENT_ID is not configured.");if(!clientSecret())throw new Error("GOOGLE_CLIENT_SECRET is not configured.");const q=new URLSearchParams({client_id:id,redirect_uri:youtubeRedirectUri(),response_type:"code",scope:"https://www.googleapis.com/auth/youtube.upload",access_type:"offline",prompt:"consent",include_granted_scopes:"true",state});return `https://accounts.google.com/o/oauth2/v2/auth?${q}`}
export async function exchangeYoutubeCode(code:string){const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:clientId(),client_secret:clientSecret(),redirect_uri:youtubeRedirectUri(),grant_type:"authorization_code"})});const data=await response.json() as {refresh_token?:string;error_description?:string};if(!response.ok||!data.refresh_token)throw new Error(data.error_description||"Google did not return a refresh token. Revoke the prior grant and authorize again.");await sql()`INSERT INTO integration_credentials(provider,encrypted_value) VALUES('youtube',${encrypt(data.refresh_token)}) ON CONFLICT(provider) DO UPDATE SET encrypted_value=EXCLUDED.encrypted_value,updated_at=NOW()`}
async function accessToken(){const rows=await sql()`SELECT encrypted_value FROM integration_credentials WHERE provider='youtube'`;const refreshToken=rows[0]?decrypt(String(rows[0].encrypted_value)):process.env.YOUTUBE_REFRESH_TOKEN;if(!refreshToken)throw new Error("YouTube OAuth authorization is required.");const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:clientId(),client_secret:clientSecret(),refresh_token:refreshToken,grant_type:"refresh_token"})});const data=await response.json() as {access_token?:string;error_description?:string};if(!response.ok||!data.access_token)throw new Error(data.error_description||"YouTube token refresh failed.");return data.access_token}
export async function uploadYoutube(uploadId:string){const rows=await sql()`SELECT y.*,m.data,m.external_url,m.mime_type FROM youtube_uploads y JOIN media_assets m ON m.upload_id=y.id AND m.kind='video' WHERE y.id=${uploadId}::uuid LIMIT 1`;if(!rows[0])throw new Error("Rendered video asset is missing.");const row=rows[0];let video=row.data?Buffer.from(row.data as Uint8Array):undefined;if(!video&&row.external_url){const media=await fetch(String(row.external_url),{signal:AbortSignal.timeout(120000)});if(!media.ok)throw new Error(`Video download failed (${media.status}).`);video=Buffer.from(await media.arrayBuffer());}if(!video)throw new Error("Video data is unavailable.");const token=await accessToken(),metadata={snippet:{title:row.title,description:row.description,tags:row.tags},status:{privacyStatus:"public",selfDeclaredMadeForKids:false}};const boundary=`aionex_${randomBytes(12).toString("hex")}`,head=Buffer.from(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: ${row.mime_type}\r\n\r\n`),tail=Buffer.from(`\r\n--${boundary}--`),body=Buffer.concat([head,video,tail]);const response=await fetch("https://www.googleapis.com/upload/youtube/v3/videos?part=snippet,status&uploadType=multipart",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":`multipart/related; boundary=${boundary}`},body});const data=await response.json() as {id?:string;error?:{message?:string}};if(!response.ok||!data.id)throw new Error(data.error?.message||"YouTube upload failed.");await sql()`UPDATE youtube_uploads SET video_id=${data.id},status='published',published_at=NOW(),updated_at=NOW() WHERE id=${uploadId}::uuid`;return {videoId:data.id}}
