import type { StoryScenario } from "./types.ts";

export const STORY_COMPOSITION_ID="aionex-story-renderscript-v2";
export type StoryCompositionElement=Record<string,unknown>&{type:string;name:string;time?:number;duration?:number;animations?:Record<string,unknown>[]};
type Element=StoryCompositionElement;
export type StoryComposition={output_format:"mp4";width:number;height:number;render_scale:number;duration:number;frame_rate:number;snapshot_time:number;background_color:string;metadata:string;elements:StoryCompositionElement[];preset?:string;priority?:string};
const fade=(duration=.35):Record<string,unknown>=>({type:"fade",duration});
const slide=(direction="up",duration=.5):Record<string,unknown>=>({type:"slide",direction,duration,easing:"cubic-out"});
const scale=(start="70%",end="100%",duration=1):Record<string,unknown>=>({type:"scale",scope:"element",start_scale:start,end_scale:end,duration,easing:"cubic-out"});
const SHAPE_PATHS={
  rectangle:"M 0% 0% L 100% 0% L 100% 100% L 0% 100% Z",
  ellipse:"M 50% 0% C 77.6% 0% 100% 22.4% 100% 50% C 100% 77.6% 77.6% 100% 50% 100% C 22.4% 100% 0% 77.6% 0% 50% C 0% 22.4% 22.4% 0% 50% 0% Z",
} as const;
const shape=(name:string,shapeName:keyof typeof SHAPE_PATHS,time:number,duration:number,props:Record<string,unknown>,animations:Record<string,unknown>[]=[fade()]):Element=>({name,type:"shape",path:SHAPE_PATHS[shapeName],time,duration,...props,animations});
const text=(name:string,value:string,time:number,duration:number,props:Record<string,unknown>={}):Element=>({name,type:"text",text:name.endsWith("energy.label")?"ENERGY 500 TO 497":name.endsWith("level1")?"LEVEL 1 | CORE":name.endsWith("level6")?"LEVEL 6 | SPARK":name.endsWith("telegram")?"@aionexweb3 | TELEGRAM MINI APP":value,time,duration,fill_color:"#FFFFFF",font_family:"Arial",font_weight:"700",x_alignment:"50%",y_alignment:"50%",...props,animations:[fade(.22),slide("up",.32)]});

function environment(prefix:string,time:number,duration:number,index:number):Element[]{const palette=["#061A2E","#061827","#0A1331","#071C29","#071526"],accent=["#22D3EE","#38BDF8","#8B5CF6","#2DD4BF","#60A5FA"];const elements:Element[]=[shape(`${prefix}.environment`,"rectangle",time,duration,{x:"50%",y:"50%",width:"100%",height:"100%",fill_color:palette[index]}),shape(`${prefix}.glow.left`,"ellipse",time,duration,{x:"14%",y:"30%",width:"72%",height:"54%",fill_color:`${accent[index]}33`,blur_radius:22},[fade(.3),scale("82%","112%",duration)]),shape(`${prefix}.glow.right`,"ellipse",time,duration,{x:"88%",y:"66%",width:"65%",height:"45%",fill_color:"#7C3AED28",blur_radius:28},[fade(.3),scale("110%","82%",duration)]),shape(`${prefix}.frame`,"rectangle",time,duration,{x:"50%",y:"50%",width:"92%",height:"92%",fill_color:"#02061700",stroke_color:`${accent[index]}88`,stroke_width:"0.18 vmin"})];
  for(let line=0;line<7;line++)elements.push(shape(`${prefix}.grid.h${line}`,"rectangle",time,duration,{x:"50%",y:`${58+line*6}%`,width:`${92-line*7}%`,height:"0.12%",fill_color:`${accent[index]}55`},[fade(.4),slide("up",.8)]));
  for(let line=0;line<5;line++)elements.push(shape(`${prefix}.grid.v${line}`,"rectangle",time,duration,{x:`${20+line*15}%`,y:"78%",width:"0.12%",height:"40%",fill_color:`${accent[index]}44`,angle:(line-2)*7},[fade(.4),slide("up",.9)]));
  for(let particle=0;particle<14;particle++){const x=8+(particle*17)%88,y=12+(particle*29)%72,size=particle%3===0?"1.1%":"0.55%";elements.push(shape(`${prefix}.particle.${particle}`,"ellipse",time,duration,{x:`${x}%`,y:`${y}%`,width:size,height:size,fill_color:particle%4===0?"#C4B5FD":"#67E8F9",shadow_color:"#22D3EE",shadow_blur:"1.2 vmin"},[fade(.2+particle*.015),slide(particle%2?"up":"down",1.2+particle*.04),scale("60%","130%",duration)]));}
  elements.push(text(`${prefix}.watermark`,"AIONEX",time,duration,{x:"50%",y:"6%",width:"38%",height:"4%",font_size:"2.8 vmin",fill_color:"#A5F3FC",letter_spacing:"18%"}));
  return elements;
}

function core(prefix:string,time:number,duration:number,x:string|number=50,y:string|number=42,size=1):Element[]{const pct=(value:number)=>`${value*size}%`,xValue=Number.parseFloat(String(x)),yValue=Number.parseFloat(String(y)),xAt=(offset=0)=>`${xValue+offset*size}%`,yAt=(offset=0)=>`${yValue+offset*size}%`;return[shape(`${prefix}.aion.outer`,"ellipse",time,duration,{x:xAt(),y:yAt(),width:pct(39),height:pct(25),fill_color:"#07182A",stroke_color:"#22D3EE",stroke_width:"0.5 vmin",shadow_color:"#22D3EE",shadow_blur:"3.2 vmin"},[fade(.2),scale("55%","100%",1),{type:"spin",duration}]),shape(`${prefix}.aion.ring1`,"ellipse",time,duration,{x:xAt(),y:yAt(),width:pct(31),height:pct(31),fill_color:"#02061722",stroke_color:"#60A5FA",stroke_width:"0.32 vmin"},[fade(.3),{type:"spin",duration:duration*.65}]),shape(`${prefix}.aion.ring2`,"ellipse",time,duration,{x:xAt(),y:yAt(),width:pct(25),height:pct(25),fill_color:"#0E749055",stroke_color:"#A5F3FC",stroke_width:"0.28 vmin",shadow_color:"#22D3EE",shadow_blur:"2 vmin"},[fade(.35),scale("80%","108%",duration)]),shape(`${prefix}.aion.face`,"ellipse",time,duration,{x:xAt(),y:yAt(),width:pct(19),height:pct(14),fill_color:"#03111F",stroke_color:"#67E8F9",stroke_width:"0.25 vmin"},[fade(.4),scale("70%","100%",.8)]),shape(`${prefix}.aion.eye.left`,"ellipse",time,duration,{x:xAt(-3.4),y:yAt(),width:pct(2.4),height:pct(1.5),fill_color:"#E0F2FE",shadow_color:"#67E8F9",shadow_blur:"1.4 vmin"},[fade(.75),scale("20%","100%",.4)]),shape(`${prefix}.aion.eye.right`,"ellipse",time,duration,{x:xAt(3.4),y:yAt(),width:pct(2.4),height:pct(1.5),fill_color:"#E0F2FE",shadow_color:"#67E8F9",shadow_blur:"1.4 vmin"},[fade(.75),scale("20%","100%",.4)]),shape(`${prefix}.aion.signal`,"rectangle",time,duration,{x:xAt(),y:yAt(6),width:pct(8),height:pct(.6),fill_color:"#22D3EE",shadow_color:"#22D3EE",shadow_blur:"1 vmin"},[fade(.7),scale("20%","100%",.5)])];}

function phone(prefix:string,time:number,duration:number,x:string|number=50,y:string|number=45,scaleValue=1):Element[]{const p=(value:number)=>`${value*scaleValue}%`,xValue=Number.parseFloat(String(x)),yValue=Number.parseFloat(String(y));return[shape(`${prefix}.phone.shadow`,"rectangle",time,duration,{x:`${xValue+1.2}%`,y:`${yValue+1.5}%`,width:p(42),height:p(66),fill_color:"#020617AA",blur_radius:7},[fade(),slide("up",.7)]),shape(`${prefix}.phone.frame`,"rectangle",time,duration,{x:`${xValue}%`,y:`${yValue}%`,width:p(42),height:p(66),fill_color:"#0F2740",stroke_color:"#67E8F9",stroke_width:"0.5 vmin",shadow_color:"#22D3EE",shadow_blur:"2 vmin"},[fade(),slide("up",.7),scale("86%","100%",.8)]),shape(`${prefix}.phone.screen`,"rectangle",time,duration,{x:`${xValue}%`,y:`${yValue}%`,width:p(37),height:p(59),fill_color:"#06101E",stroke_color:"#1E3A5F",stroke_width:"0.22 vmin"}),shape(`${prefix}.phone.speaker`,"rectangle",time,duration,{x:`${xValue}%`,y:`${yValue-28*scaleValue}%`,width:p(8),height:p(.7),fill_color:"#64748B"})];}

function sceneOne(time:number,duration:number):Element[]{const p="s1";const result=[...environment(p,time,duration,0)];for(let i=0;i<5;i++)result.push(shape(`${p}.lab.column.${i}`,"rectangle",time,duration,{x:`${9+i*21}%`,y:"47%",width:"7%",height:`${46+(i%2)*12}%`,fill_color:i%2?"#0C4A6E55":"#155E7555",stroke_color:"#22D3EE55",stroke_width:"0.15 vmin"},[fade(.3+i*.08),slide("up",.7+i*.1)]));result.push(...core(p,time,duration));result.push(text(`${p}.logo`,`AIONEX`,time,duration,{x:"50%",y:"14%",width:"70%",height:"9%",font_size:"8 vmin",fill_color:"#A5F3FC",letter_spacing:"18%",shadow_color:"#22D3EE",shadow_blur:"1.5 vmin"}));return result;}
function sceneTwo(time:number,duration:number):Element[]{const p="s2",result=[...environment(p,time,duration,1),...phone(p,time,duration,"50%","46%",1)];result.push(...core(`${p}.mini`,time,duration,"50%","39%",.56));result.push(shape(`${p}.energy.track`,"rectangle",time,duration,{x:"50%",y:"57%",width:"28%",height:"1.8%",fill_color:"#1E293B"}));result.push(shape(`${p}.energy.value`,"rectangle",time,duration,{x:"48.5%",y:"57%",width:"25%",height:"1.8%",fill_color:"#FBBF24",shadow_color:"#F59E0B",shadow_blur:".8 vmin"},[fade(),scale("100%","89%",duration)]));result.push(shape(`${p}.xp.track`,"rectangle",time,duration,{x:"50%",y:"61%",width:"28%",height:"1.5%",fill_color:"#1E293B"}));result.push(shape(`${p}.xp.value`,"rectangle",time,duration,{x:"45%",y:"61%",width:"18%",height:"1.5%",fill_color:"#8B5CF6",shadow_color:"#8B5CF6",shadow_blur:".8 vmin"},[fade(),scale("45%","100%",duration)]));result.push(text(`${p}.energy.label`,`ENERGY 500 → 497`,time,duration,{x:"50%",y:"65%",width:"30%",height:"4%",font_size:"2.6 vmin",fill_color:"#FDE68A"}));for(const [index,reward] of ["+1","+2","+5"].entries())result.push(text(`${p}.reward.${index}`,reward,time+1+index*1.7,2.2,{x:`${31+index*19}%`,y:`${35-index*5}%`,width:"12%",height:"5%",font_size:"5 vmin",fill_color:index===2?"#C4B5FD":"#67E8F9",shadow_color:"#22D3EE",shadow_blur:"1 vmin"}));result.push(shape(`${p}.finger`,"ellipse",time+1,duration-1,{x:"69%",y:"47%",width:"8%",height:"14%",fill_color:"#DBEAFE",angle:-28,shadow_color:"#60A5FA",shadow_blur:"1.2 vmin"},[fade(),slide("down",.7),scale("100%","82%",1.4)]));for(let i=0;i<4;i++)result.push(shape(`${p}.tapwave.${i}`,"ellipse",time+1+i*.7,2.5,{x:"56%",y:"44%",width:`${8+i*6}%`,height:`${8+i*6}%`,fill_color:"#00000000",stroke_color:`#67E8F9${99-i*18}`,stroke_width:"0.3 vmin"},[fade(.1),scale("30%","150%",2)]));return result;}
function sceneThree(time:number,duration:number):Element[]{const p="s3",result=[...environment(p,time,duration,2)];result.push(...core(`${p}.core`,time,duration*.52,"35%","43%",.7));result.push(...core(`${p}.spark`,time+duration*.42,duration*.58,"66%","43%",.92));for(let i=0;i<5;i++)result.push(shape(`${p}.evolution.ring.${i}`,"ellipse",time+duration*.35,duration*.65,{x:"66%",y:"43%",width:`${26+i*8}%`,height:`${26+i*8}%`,fill_color:"#00000000",stroke_color:i%2?"#8B5CF6":"#22D3EE",stroke_width:"0.28 vmin",shadow_color:"#67E8F9",shadow_blur:"1 vmin"},[fade(.15+i*.08),scale("30%","120%",1.2+i*.12),{type:"spin",duration:2.5+i*.5}]));result.push(shape(`${p}.xp.track`,"rectangle",time,duration,{x:"50%",y:"72%",width:"72%",height:"3%",fill_color:"#1E293B"}));result.push(shape(`${p}.xp.fill`,"rectangle",time,duration,{x:"50%",y:"72%",width:"70%",height:"3%",fill_color:"#8B5CF6",shadow_color:"#A78BFA",shadow_blur:"1.2 vmin"},[fade(),scale("8%","100%",duration*.7)]));result.push(text(`${p}.level1`,`LEVEL 1 · CORE`,time,duration*.48,{x:"35%",y:"62%",width:"30%",height:"6%",font_size:"4 vmin",fill_color:"#67E8F9"}),text(`${p}.level6`,`LEVEL 6 · SPARK`,time+duration*.45,duration*.55,{x:"66%",y:"62%",width:"34%",height:"6%",font_size:"4 vmin",fill_color:"#C4B5FD"}));return result;}
function sceneFour(time:number,duration:number):Element[]{const p="s4",result=[...environment(p,time,duration,3)];for(let i=0;i<3;i++){const y=24+i*13;result.push(shape(`${p}.task.${i}`,"rectangle",time+i*.3,duration-i*.3,{x:"30%",y:`${y}%`,width:"46%",height:"10%",fill_color:"#0F2D3D",stroke_color:"#2DD4BF",stroke_width:"0.25 vmin"},[fade(),slide("left",.55)]));result.push(shape(`${p}.task.check.${i}`,"ellipse",time+1+i*.4,duration-1-i*.4,{x:"46%",y:`${y}%`,width:"4%",height:"4%",fill_color:"#34D399",shadow_color:"#34D399",shadow_blur:"1 vmin"},[fade(),scale("10%","100%",.5)]));}for(let node=0;node<9;node++){const x=55+(node*13)%39,y=20+(node*23)%43;result.push(shape(`${p}.network.node.${node}`,"ellipse",time+node*.12,duration-node*.12,{x:`${x}%`,y:`${y}%`,width:node===0?"5%":"2.4%",height:node===0?"5%":"2.4%",fill_color:node===0?"#C4B5FD":"#67E8F9",shadow_color:"#22D3EE",shadow_blur:"1 vmin"},[fade(),scale("20%","100%",.5)]));if(node>0)result.push(shape(`${p}.network.link.${node}`,"rectangle",time+node*.12,duration-node*.12,{x:`${(x+72)/2}%`,y:`${(y+43)/2}%`,width:`${Math.max(6,Math.abs(72-x))}%`,height:"0.18%",fill_color:"#22D3EE77",angle:(y-43)*.7},[fade(.25),scale("0%","100%",.6)]));}result.push(...core(`${p}.celebrate`,time+duration*.45,duration*.55,"50%","72%",.48));result.push(shape(`${p}.badge`,"ellipse",time+duration*.55,duration*.45,{x:"73%",y:"67%",width:"14%",height:"14%",fill_color:"#7C3AED",stroke_color:"#C4B5FD",stroke_width:"0.5 vmin",shadow_color:"#8B5CF6",shadow_blur:"2 vmin"},[fade(),scale("20%","110%",.7),{type:"spin",duration:2}]));return result;}
function sceneFive(time:number,duration:number):Element[]{const p="s5",result=[...environment(p,time,duration,4),...core(p,time,duration,"38%","42%",.82),...phone(`${p}.miniapp`,time,duration,"73%","43%",.56)];result.push(shape(`${p}.cta.button`,"rectangle",time+1,duration-1,{x:"50%",y:"70%",width:"62%",height:"9%",fill_color:"#22D3EE",stroke_color:"#BAE6FD",stroke_width:"0.3 vmin",shadow_color:"#22D3EE",shadow_blur:"2.5 vmin"},[fade(),slide("up",.6),scale("88%","104%",duration-1)]));result.push(text(`${p}.cta.label`,`OPEN AIONEX`,time+1,duration-1,{x:"50%",y:"70%",width:"58%",height:"7%",font_size:"5.4 vmin",fill_color:"#020617"}));result.push(text(`${p}.brand`,`AIONEX`,time,duration,{x:"50%",y:"14%",width:"76%",height:"10%",font_size:"8.5 vmin",fill_color:"#A5F3FC",letter_spacing:"18%",shadow_color:"#22D3EE",shadow_blur:"1.8 vmin"}));result.push(text(`${p}.telegram`,`@aionexweb3 · TELEGRAM MINI APP`,time,duration,{x:"50%",y:"82%",width:"82%",height:"6%",font_size:"3.4 vmin",fill_color:"#93C5FD"}));for(let i=0;i<6;i++)result.push(shape(`${p}.outro.ring.${i}`,"ellipse",time+i*.2,duration-i*.2,{x:"50%",y:"50%",width:`${30+i*14}%`,height:`${30+i*14}%`,fill_color:"#00000000",stroke_color:i%2?"#8B5CF655":"#22D3EE66",stroke_width:"0.22 vmin"},[fade(.15),scale("45%","130%",duration),{type:"spin",duration:3+i*.4}]));return result;}

export function buildStoryComposition(scenario:StoryScenario,audioUrl:string):StoryComposition{const sceneBuilders=[sceneOne,sceneTwo,sceneThree,sceneFour,sceneFive],elements:Element[]=[{name:"global.narration",type:"audio",source:audioUrl,time:0,duration:scenario.durationSeconds} as Element];scenario.scenes.slice(0,5).forEach((scene,index)=>{const duration=scene.endSeconds-scene.startSeconds;elements.push(...sceneBuilders[index](scene.startSeconds,duration));elements.push(text(`s${index+1}.subtitle`,scene.subtitleText,scene.startSeconds,duration,{x:"50%",y:"91%",width:"86%",height:"12%",font_size:"4.5 vmin",fill_color:"#FFFFFF",stroke_color:"#020617",stroke_width:"0.55 vmin",background_color:"#02061799"}));});const composition:StoryComposition={output_format:"mp4",width:1080,height:1920,render_scale:1,duration:scenario.durationSeconds,frame_rate:30,snapshot_time:25,background_color:"#030814",metadata:JSON.stringify({compositionId:STORY_COMPOSITION_ID,scenarioKey:scenario.scenarioKey}),elements};
// Allow optional provider-specific overrides via environment variables (non-breaking):
if (process && process.env) {
  if (process.env.CREATOMATE_PRESET) composition["preset"] = process.env.CREATOMATE_PRESET;
  if (process.env.CREATOMATE_PRIORITY) composition["priority"] = process.env.CREATOMATE_PRIORITY;
  if (process.env.CREATOMATE_RENDER_SCALE) composition["render_scale"] = Number(process.env.CREATOMATE_RENDER_SCALE);
}
return composition;}

export function compositionManifest(composition:ReturnType<typeof buildStoryComposition>){const elements=composition.elements as Element[],scenes=[1,2,3,4,5].map(position=>{const prefix=`s${position}.`,items=elements.filter(element=>element.name.startsWith(prefix)),nonText=items.filter(element=>element.type!=="text"),animated=items.filter(element=>Boolean(element.animations?.length));return{position,elementCount:items.length,nonTextCount:nonText.length,animatedCount:animated.length,hasPresenter:items.some(element=>element.name.includes(".aion.")),hasBranding:items.some(element=>/logo|brand|telegram|watermark/.test(element.name)),hasEnvironment:items.some(element=>element.name.includes(".environment")),hasPhone:items.some(element=>element.name.includes(".phone."))};});const textCount=elements.filter(element=>element.type==="text").length;return{compositionId:STORY_COMPOSITION_ID,totalElements:elements.length,textCount,nonTextCount:elements.length-textCount,textRatio:textCount/elements.length,hasAudio:elements.some(element=>element.type==="audio"),hasPresenter:elements.some(element=>element.name.includes(".aion.")),hasMiniApp:elements.some(element=>element.name.includes("phone.screen")),scenes};}
