import "server-only";

import { createHash } from "node:crypto";
import { neon } from "@neondatabase/serverless";
import { publishTelegram, publishX, telegramChannelId } from "@/lib/automation/publish";
import { uploadYoutube } from "@/lib/automation/youtube";
import { storySettings } from "./service";

const database=()=>{if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is not configured.");return neon(process.env.DATABASE_URL);};
export async function publishStoryScenario(scenarioId:string){const settings=await storySettings();if(!settings.publishingEnabled||settings.dryRun||settings.previewOnly||settings.emergencyPause)throw new Error("Story Engine public publishing is disabled by safety settings.");const sql=database(),rows=await sql`SELECT s.*,r.video_url,r.provider_job_id,r.duration_seconds FROM story_scenarios s JOIN story_render_jobs r ON r.scenario_id=s.id AND r.status='ready' WHERE s.id=${scenarioId}::uuid AND s.status IN ('approved','previewed') ORDER BY r.completed_at DESC LIMIT 1`;const story=rows[0];if(!story?.video_url)throw new Error("Validated Story Engine video is unavailable.");const channelId=telegramChannelId(),hash=createHash("sha256").update(`story:${scenarioId}:${story.fingerprint}`).digest("hex");const generated=await sql`INSERT INTO generated_content(content_hash,topic,format,title,body,metadata) VALUES(${hash},${story.topic},'aion_story_video',${story.title},${story.narration},${JSON.stringify({storyScenarioId:scenarioId})}::jsonb) ON CONFLICT(content_hash) DO UPDATE SET metadata=generated_content.metadata RETURNING id`;const contentId=String(generated[0].id);const warnings:string[]=[];let telegramMessageId:string|undefined,youtubeVideoId:string|undefined;let xPostId:string|undefined;const telegram=await sql`SELECT * FROM story_deliveries WHERE scenario_id=${scenarioId}::uuid AND platform='telegram' AND status='published'`;if(telegram[0])telegramMessageId=String(telegram[0].external_id);else{telegramMessageId=await publishTelegram(String(story.telegram_caption),String(story.video_url));await sql`INSERT INTO story_deliveries(scenario_id,platform,status,external_id,external_url,attempts,published_at) VALUES(${scenarioId}::uuid,'telegram','published',${telegramMessageId},${`https://t.me/aionexweb3/${telegramMessageId}`},1,NOW()) ON CONFLICT(scenario_id,platform) DO UPDATE SET status='published',external_id=EXCLUDED.external_id,external_url=EXCLUDED.external_url,published_at=NOW(),last_error=NULL,attempts=story_deliveries.attempts+1`;await sql`INSERT INTO telegram_posts(content_id,message_id,chat_id,video_url,status,published_at) VALUES(${contentId}::uuid,${telegramMessageId},${channelId},${story.video_url},'published',NOW()) ON CONFLICT(content_id) DO NOTHING`;}
  const youtube=await sql`SELECT * FROM story_deliveries WHERE scenario_id=${scenarioId}::uuid AND platform='youtube' AND status='published'`;if(youtube[0])youtubeVideoId=String(youtube[0].external_id);else try{const upload=await sql`INSERT INTO youtube_uploads(content_id,title,description,tags,voice_script,subtitles,render_job,status) VALUES(${contentId}::uuid,${String(story.youtube_title).slice(0,100)},${story.youtube_description},${JSON.stringify(story.hashtags)}::jsonb,${story.narration},${story.narration},${JSON.stringify({id:story.provider_job_id,url:story.video_url,duration:Number(story.duration_seconds)})}::jsonb,'rendered') ON CONFLICT(content_id) DO UPDATE SET render_job=EXCLUDED.render_job RETURNING id`;await sql`INSERT INTO media_assets(upload_id,kind,mime_type,external_url,metadata) VALUES(${upload[0].id}::uuid,'video','video/mp4',${story.video_url},${JSON.stringify({storyScenarioId:scenarioId})}::jsonb)`;youtubeVideoId=(await uploadYoutube(String(upload[0].id))).videoId;await sql`INSERT INTO story_deliveries(scenario_id,platform,status,external_id,attempts,published_at) VALUES(${scenarioId}::uuid,'youtube','published',${youtubeVideoId},1,NOW()) ON CONFLICT(scenario_id,platform) DO UPDATE SET status='published',external_id=EXCLUDED.external_id,published_at=NOW(),last_error=NULL,attempts=story_deliveries.attempts+1`;}catch(error){const message=error instanceof Error?error.message:"YouTube failed";warnings.push(message);await recordFailure(scenarioId,"youtube",message);}
  const x=await sql`SELECT * FROM story_deliveries WHERE scenario_id=${scenarioId}::uuid AND platform='x' AND status='published'`;if(x[0])xPostId=String(x[0].external_id);else try{xPostId=await publishX(String(story.x_caption).slice(0,280));await sql`INSERT INTO story_deliveries(scenario_id,platform,status,external_id,attempts,published_at) VALUES(${scenarioId}::uuid,'x','published',${xPostId},1,NOW()) ON CONFLICT(scenario_id,platform) DO UPDATE SET status='published',external_id=EXCLUDED.external_id,published_at=NOW(),last_error=NULL,attempts=story_deliveries.attempts+1`;}catch(error){const message=error instanceof Error?error.message:"X failed";warnings.push(message);await recordFailure(scenarioId,"x",message);}
  await sql`UPDATE story_scenarios SET status='published',updated_at=NOW() WHERE id=${scenarioId}::uuid`;return{scenarioId,telegramMessageId,youtubeVideoId,xPostId,warnings};}
async function recordFailure(scenarioId:string,platform:"youtube"|"x",message:string){await database()`INSERT INTO story_deliveries(scenario_id,platform,status,attempts,last_error) VALUES(${scenarioId}::uuid,${platform},'failed',1,${message.slice(0,1000)}) ON CONFLICT(scenario_id,platform) DO UPDATE SET status='failed',attempts=story_deliveries.attempts+1,last_error=EXCLUDED.last_error,updated_at=NOW()`;}
