import { defaultScenePlan, templateForCategory } from "./catalog.ts";
import type { StoryScenario } from "./types.ts";

const week = [
  {categoryKey:"ecosystem_overview",topic:"What is AIONEX?",title:"Meet the Intelligence That Evolves With You",hook:"What if your AI grew stronger every time you showed up?",parts:["Most digital tools stay exactly the same, no matter how you use them.","AIONEX connects a personal AION character with verified activity, learning, missions, and community progress.","Inside the Telegram Mini App, your taps use energy, add AXP and XP, and move AION through visible evolution stages.","Open AIONEX and begin building an intelligence that reflects your journey."],cta:"Open AIONEX in Telegram and awaken your AION."},
  {categoryKey:"tap_mining",topic:"How tap-to-earn mining works",title:"Every Verified Tap Moves AION Forward",hook:"A tap is small. A verified streak of taps can transform AION.",parts:["Tap-to-earn should feel immediate without trusting an unverified client counter.","AIONEX reacts instantly, batches your taps safely, and reconciles rewards with the server.","Energy falls as you tap, AXP and XP advance, while critical taps and combos create stronger moments.","Tap AION, watch the response, and build progress one verified action at a time."],cta:"Open the Mine tab and send your first verified signal."},
  {categoryKey:"evolution",topic:"How AION evolves with levels",title:"Seven Forms. One AION Journey",hook:"Your AION is not a static icon—it has seven forms to unlock.",parts:["Progress without visible change quickly loses meaning.","AIONEX turns XP and levels into a clear evolution path from Core and Spark to Drone, Guardian, Quantum, Ascendant, and Prime.","Each stage has its own energy form, motion language, and milestone range.","Build XP through verified activity and discover which form your AION becomes next."],cta:"Check your Profile to preview every AION evolution stage."},
  {categoryKey:"energy",topic:"How energy regeneration works",title:"AION Energy Always Has a Rhythm",hook:"Low energy is not the end of mining—it is part of the strategy.",parts:["Repeated taps consume energy so progress stays bounded and server-authoritative.","AIONEX restores energy over time, including safe offline regeneration with a configured cap.","The live meter shows what remains, while regeneration timing tells you when AION is ready again.","Use your energy, let the core recharge, and return for the next session."],cta:"Open AIONEX and check your live energy chamber."},
  {categoryKey:"tasks",topic:"How tasks and daily rewards work",title:"Missions Give Every Day a Direction",hook:"AION grows through more than tapping.",parts:["A daily experience needs useful goals, not an endless list of random actions.","AIONEX missions show the reward, progress, verification method, and claim state before you act.","Daily rewards build streaks, while verified milestones unlock AXP, XP, and achievements without client-only claims.","Choose a mission, complete its proof, and let AION celebrate the result."],cta:"Open Tasks and choose today’s verified mission."},
  {categoryKey:"referrals",topic:"How referrals grow the community",title:"One Invitation Can Become a Network",hook:"Community growth should reward real people, not repeated devices.",parts:["Referral systems lose trust when duplicate accounts can claim the same reward.","AIONEX gives every creator a unique link and records verified joins with cross-account abuse protection.","The network view tracks invited users, milestone progress, and community rewards.","Share your signal with one trusted friend and grow the AIONEX network safely."],cta:"Open Invite, copy your personal link, and grow together."},
  {categoryKey:"aion_ai",topic:"How AION AI helps users",title:"Ask the Same AION That You Evolve",hook:"Your AI companion should understand the ecosystem you are building in.",parts:["Generic assistants feel disconnected from your product journey.","AION AI keeps a stable conversation, streams readable answers, and carries the same visual identity as your evolving character.","Use it for AIONEX guidance, Web3 education, wallet safety, and clear explanations—not guaranteed returns or invented claims.","Ask a useful question and turn the answer into your next informed action."],cta:"Open AION AI and start a conversation with your evolving intelligence."},
] as const;

export function initialStoryPreviews(day="2026-07-15"):StoryScenario[]{return week.map((item,index)=>{const sceneNarration=[item.hook,...item.parts];const duration=50;const base=defaultScenePlan(duration,item.categoryKey);const scenes=base.map((scene,sceneIndex)=>({ ...scene,narration:sceneNarration[sceneIndex],onScreenText:sceneIndex===0?item.hook:item.parts[Math.max(0,sceneIndex-1)].split(/[.!?]/)[0],subtitleText:sceneNarration[sceneIndex],visualInstructions:[`Use ${templateForCategory(item.categoryKey)} with purposeful AIONEX motion.`,sceneIndex===3?"Show a legible product-feature demonstration.":"Keep AION or the AIONEX identity visible."],motionInstructions:[sceneIndex===0?"Fast energy reveal in the first three seconds.":"Use transform, opacity, depth, and parallax transitions.","Never leave a static black frame."],assetReferences:[]}));const narration=sceneNarration.join(" ");const tag=item.categoryKey.replaceAll("_","");return{scenarioKey:`week1-${day}-${index+1}`,categoryKey:item.categoryKey,topic:item.topic,title:item.title,hook:item.hook,narration,presenter:"animated_core",durationSeconds:duration,thumbnailText:item.title.toUpperCase().slice(0,48),telegramCaption:`${item.title}\n\n${item.cta}\n\n#AIONEX #AION`,youtubeTitle:`${item.title} | AIONEX`,youtubeDescription:`${narration}\n\n${item.cta}\n\nEducational content. No investment advice.`,xCaption:`${item.hook} ${item.cta}`.slice(0,260),hashtags:["AIONEX","AION",tag],callToAction:item.cta,factualSafetyNotes:["Claims are limited to implemented AIONEX functionality.","No earnings, price, partnership, or release-date claims."],sourceReferences:["AIONEX repository and production feature configuration"],scenes};});}
