import Link from "next/link";
import { AnalysisPanel } from "./analysis-panel";
import { MarketOverview } from "./market-overview";
import { TradingChart } from "./trading-chart";

const signals = [
  ["BTC", "BUY", "78", "Momentum and volume align above the 20D trend."],
  ["ETH", "HOLD", "61", "Range conditions remain constructive; await confirmation."],
  ["SOL", "SELL", "54", "Short-term momentum is cooling near resistance."],
];

export default function DashboardPage() {
  return <main className="min-h-screen bg-[#030812] text-white"><header className="sticky top-0 z-20 border-b border-white/10 bg-[#030812]/80 px-5 py-4 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between"><Link href="/" className="flex items-center gap-2.5 font-bold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg bg-gradient-to-br from-cyan-300 to-blue-600 text-sm text-[#02050b]">A</span>AIONEX <em className="not-italic text-cyan-300">AI</em></Link><div className="flex items-center gap-3"><span className="hidden items-center gap-2 text-xs text-slate-400 sm:flex"><i className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_10px_#4ade80]" /> All systems live</span><Link href="/" className="rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-300 transition hover:border-cyan-300/50 hover:text-cyan-200">Landing page</Link></div></div></header><div className="mx-auto max-w-7xl px-5 py-10 sm:py-12"><div className="mb-10 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="dashboard-kicker">AIONEX TERMINAL <span className="ml-2 inline-flex items-center gap-1.5 rounded-full border border-emerald-300/15 bg-emerald-300/[.08] px-2 py-1 text-[9px] text-emerald-200"><i className="h-1.5 w-1.5 rounded-full bg-emerald-300 shadow-[0_0_7px_#6ee7b7]" /> LIVE</span></p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Good morning, Alex.</h1><p className="mt-3 text-slate-400">Your AI-powered view of the market, updated in real time.</p></div><div className="dashboard-card flex items-center gap-4 px-5 py-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-cyan-300/15 text-cyan-200">✦</div><div><p className="text-xs text-slate-400">AIONEX market sentiment</p><p className="font-semibold text-cyan-100">Bullish <span className="ml-1 text-xs font-normal text-emerald-300">+12.4%</span></p></div></div></div><MarketOverview /><div className="mt-8 grid gap-8 xl:grid-cols-[1.55fr_.75fr]"><TradingChart /><Portfolio /></div><section className="dashboard-card mt-8 p-6"><div className="flex items-start justify-between"><div><p className="dashboard-kicker">AIONEX INSIGHTS</p><h2 className="mt-1 text-xl font-semibold">AI trading signals</h2></div><span className="rounded-full bg-cyan-300/10 px-3 py-1.5 text-xs text-cyan-200">Updated now</span></div><div className="mt-6 divide-y divide-white/10">{signals.map(([symbol, signal, confidence, note]) => <div key={symbol} className="grid gap-3 py-5 sm:grid-cols-[70px_80px_1fr_auto] sm:items-center"><strong className="text-lg">{symbol}</strong><SignalBadge signal={signal} /><p className="text-sm leading-6 text-slate-400">{note}</p><span className="text-sm text-cyan-100">{confidence}% <small className="block text-[10px] text-slate-500">confidence</small></span></div>)}</div></section><div className="mt-8"><AnalysisPanel /></div></div></main>;
}

function SignalBadge({ signal }: { signal: string }) { const color = signal === "BUY" ? "bg-emerald-400/10 text-emerald-300" : signal === "SELL" ? "bg-rose-400/10 text-rose-300" : "bg-amber-300/10 text-amber-200"; return <span className={`w-fit rounded-full px-2.5 py-1 text-[11px] font-bold ${color}`}>{signal}</span>; }
function Portfolio() { const rows = [["Bitcoin", "48.6%", "#f59e0b"], ["Ethereum", "31.2%", "#818cf8"], ["Solana", "12.4%", "#e879f9"], ["USDC", "7.8%", "#22d3ee"]]; return <aside className="dashboard-card p-6"><p className="dashboard-kicker">YOUR PORTFOLIO</p><h2 className="mt-1 text-xl font-semibold">Overview</h2><p className="mt-9 text-sm text-slate-400">Total balance</p><p className="mt-1 text-4xl font-semibold tracking-tight">$84,297.12</p><p className="mt-2 text-sm text-emerald-300">↗ $2,441.89 (2.98%) today</p><div className="mt-9 space-y-5">{rows.map(([name, amount, color]) => <div key={name}><div className="mb-2 flex justify-between text-sm"><span className="text-slate-300">{name}</span><span className="text-slate-400">{amount}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full" style={{ width: amount, backgroundColor: color }} /></div></div>)}</div></aside>; }
