import { applyReferral,claimTask,completePendingTask,consumeLinkCode,findOrCreateIdentity,getProfile,leaderboard,listTasks,mine,miningStats,rewardHistory } from "@/lib/rewards/db";
import { logError } from "@/lib/observability/logger";
import { verifyTask } from "@/lib/rewards/verification";
import { OFFICIAL_LINKS } from "@/lib/social/config";

type TelegramUser={id:number;username?:string;first_name?:string;last_name?:string};
type Update={message?:{chat:{id:number};from?:TelegramUser;text?:string};callback_query?:{id:string;from:TelegramUser;data?:string;message?:{chat:{id:number}}}};
const site=()=>OFFICIAL_LINKS.website;
const miniAppUrl=()=>`${site()}/rewards`;
const launchKeyboard={inline_keyboard:[[{text:"🚀 Open AIONEX",web_app:{url:miniAppUrl()}}]]};
const fallbackKeyboard={inline_keyboard:[[{text:"🚀 Open Mini App",web_app:{url:miniAppUrl()}}],[{text:"⛏ Mine",callback_data:"mine"},{text:"👤 Profile",callback_data:"profile"}],[{text:"✅ Tasks",callback_data:"tasks"},{text:"🎁 Rewards",callback_data:"rewards"}],[{text:"Verify Telegram",callback_data:"social_verify:telegram"},{text:"Verify X",callback_data:"social_verify:x"},{text:"Verify YouTube",callback_data:"social_verify:youtube"}],[{text:"Official Telegram",url:OFFICIAL_LINKS.telegram},{text:"Official X",url:OFFICIAL_LINKS.x},{text:"Official YouTube",url:OFFICIAL_LINKS.youtube}],[{text:"🏆 Leaderboard",callback_data:"leaderboard"},{text:"👥 Invite",callback_data:"invite"}],[{text:"Help",callback_data:"help"}]]};
async function api(method:string,payload:Record<string,unknown>){const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)throw new Error("TELEGRAM_BOT_TOKEN is not configured.");const response=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:"POST",signal:AbortSignal.timeout(10_000),headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error(`Telegram ${method} failed (${response.status}).`);}
async function send(chatId:number,text:string,replyMarkup:Record<string,unknown>=fallbackKeyboard){await api("sendMessage",{chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true,reply_markup:replyMarkup});}
async function verifySocial(chatId:number,userId:string,provider:string){const tasks=await listTasks(userId);const task=tasks.find(t=>provider==="telegram"?t.category==="telegram_join":provider==="x"?t.category==="x_follow":t.category==="youtube_subscribe");if(!task)return send(chatId,"This official social task is currently disabled.");const verification=await verifyTask(userId,task.id);if(task.claimStatus==="pending"){const completed=verification.verified?await completePendingTask(userId,task.id,verification.message):null;return send(chatId,completed?"✅ Verification complete and reward claimed.":`⏳ ${verification.message}`);}const claim=await claimTask(userId,task.id,{source:"telegram_bot"},verification.verified);return send(chatId,claim?(verification.verified?"✅ Verification complete and reward claimed.":`⏳ ${verification.message}`):"This reward was already submitted or claimed.");}
async function taskMenu(chatId:number,userId:string){const tasks=await listTasks(userId);const rows=tasks.slice(0,8).flatMap(task=>{const open=task.taskUrl?[{text:`Open ${task.icon}`,url:task.taskUrl}]:[];const action=task.completed?{text:"✅ Completed",callback_data:"noop"}:task.claimStatus==="pending"?{text:`Verify · +${task.rewardAxp} AXP / +${task.rewardXp} XP`,callback_data:`task_verify:${task.id}`}:{text:`Claim · +${task.rewardAxp} AXP / +${task.rewardXp} XP`,callback_data:`task_claim:${task.id}`};return[[...open,action]];});rows.push([{text:"← Back",callback_data:"start"}]);await send(chatId,`<b>Available tasks</b>\n\n${tasks.slice(0,8).map(t=>`${t.icon} <b>${t.title}</b>\n${t.rewardAxp} AXP · ${t.rewardXp} XP · ${t.difficulty}`).join("\n\n")||"No active tasks."}`,{inline_keyboard:rows});}
const identity=(user:TelegramUser)=>findOrCreateIdentity("telegram",String(user.id),{username:user.username,firstName:user.first_name,lastName:user.last_name});
async function content(command:string,userId:string){
  if(command==="profile"){const p=await getProfile(userId);return p?`<b>${p.displayName}</b>\nLevel ${p.level} · ${p.xp} XP\n${p.axpBalance.toLocaleString()} AXP · Rank #${p.rank}\n🔥 ${p.loginStreak} day streak · 👥 ${p.referralCount} invites`:"Profile unavailable.";}
  if(command==="mine"){const result=await mine(userId);if(!result){const s=await miningStats(userId);return `⏳ Mining is on cooldown. One claim is available every ${s.cooldown_hours} hours.`;}return `⛏ <b>Mining complete</b>\nYour AXP and XP were added securely.`;}
  if(command==="tasks"){const tasks=await listTasks(userId);return tasks.length?`<b>Available tasks</b>\n\n${tasks.slice(0,8).map(t=>`${t.completed?"✅":"•"} ${t.title} — +${t.rewardAxp} AXP`).join("\n")}\n\nOpen the Rewards Hub to submit evidence.`:"No active tasks right now.";}
  if(command==="rewards"){const [p,h]=await Promise.all([getProfile(userId),rewardHistory(userId,5)]);return `<b>Rewards</b>\n${p?.axpBalance.toLocaleString()||0} AXP · ${p?.xp||0} XP\n🔥 ${p?.loginStreak||0} day streak\n\n<b>Recent activity</b>\n${h.map(x=>`${Number(x.amount)>0?"+":""}${x.amount} AXP · ${String(x.reason).replaceAll("_"," ")}`).join("\n")||"No rewards yet."}`;}
  if(command==="leaderboard"){const rows=await leaderboard(10);return `<b>AXP Leaderboard</b>\n\n${rows.map(r=>`${r.rank}. ${r.display_name} — ${Number(r.lifetime_axp).toLocaleString()} AXP`).join("\n")||"No rankings yet."}`;}
  if(command==="invite"){const p=await getProfile(userId),username=process.env.TELEGRAM_BOT_USERNAME?.replace(/^@/,"");return `<b>Invite explorers</b>\nReferral code: <code>${p?.referralCode}</code>\n${username?`Referral link: https://t.me/${username}?start=ref_${p?.referralCode}`:`Official community: ${OFFICIAL_LINKS.telegram}`}`;}
  if(command==="help")return `<b>AIONEX Rewards Bot</b>\n/start — main menu\n/profile — account and XP\n/mine — 24-hour mining claim\n/tasks — active tasks\n/rewards — history and streak\n/leaderboard — top explorers\n/invite — referral link\n/help — this guide`;
  return `<b>Welcome to AIONEX V3</b>\n\nYour premium mining, rewards, AI, wallet, task, and referral experience is ready. Tap <b>Open AIONEX V3</b> below to launch the Mini App inside Telegram.`;
}

export async function POST(request:Request){
  const secret=process.env.TELEGRAM_WEBHOOK_SECRET;if(!secret||request.headers.get("x-telegram-bot-api-secret-token")!==secret)return Response.json({error:"Unauthorized"},{status:401});
  try{const update=await request.json() as Update;const callback=update.callback_query;const message=update.message;const user=callback?.from||message?.from;const chatId=callback?.message?.chat.id||message?.chat.id;if(!user||!chatId)return Response.json({ok:true});
    const userId=await identity(user);let command=(callback?.data||message?.text?.split(/\s+/)[0].replace(/^\//,"")||"start").toLowerCase();
    const startArg=message?.text?.match(/^\/start\s+(.+)$/)?.[1];
    if(startArg?.startsWith("link_")){const linked=await consumeLinkCode(startArg.slice(5),String(user.id),{username:user.username,firstName:user.first_name,lastName:user.last_name});await send(chatId,linked?"✅ Accounts linked. Telegram and your wallet now share one AXP balance.":"This link code is invalid, expired, or already used.");}
    else if(command.startsWith("social_verify:")){await verifySocial(chatId,userId,command.slice(14));}
    else if(command.startsWith("task_claim:")){const id=command.slice(11),verification=await verifyTask(userId,id);try{const claim=await claimTask(userId,id,{source:"telegram_bot",verificationMessage:verification.message},verification.verified);await send(chatId,claim?(verification.verified?"✅ Task completed. AXP and XP added.":`⏳ ${verification.message}`):"This task was already claimed for the current period.");}catch(error){if(error instanceof Error&&error.message==="Task is unavailable.")await send(chatId,"This task is no longer available. Open /tasks to view the current list.");else throw error;}}
    else if(command.startsWith("task_verify:")){const id=command.slice(12),verification=await verifyTask(userId,id);const claim=verification.verified?await completePendingTask(userId,id,verification.message):null;await send(chatId,claim?"✅ Verified. AXP and XP added.":`⏳ ${verification.message}`);}
    else{if(startArg?.startsWith("ref_"))await applyReferral(userId,startArg.slice(4).trim().toUpperCase());if(command==="tasks")await taskMenu(chatId,userId);else{if(!["start","profile","mine","rewards","leaderboard","invite","help","noop"].includes(command))command="help";if(command!=="noop")await send(chatId,await content(command,userId),command==="start"?launchKeyboard:fallbackKeyboard);}}
    if(callback)await api("answerCallbackQuery",{callback_query_id:callback.id});return Response.json({ok:true});
  }catch(error){logError("telegram.webhook",error);return Response.json({error:"Webhook processing failed."},{status:500});}
}
